<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Pesquisar</name>
   <tag></tag>
   <elementGuidId>d886b1bb-5faa-4263-837e-411f4e668485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anTLZ1Refresh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anTLZ1Refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>825bed61-c672-4c43-b6dd-a6109d79f45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>41c2d767-7c3f-40e8-8310-794083251855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>b9d22ecd-fb51-43eb-ade8-620d0cbe0a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton</value>
      <webElementGuid>9c74a274-bc0c-4379-b0a6-4488618a72d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a866f18a-7ac5-4156-8b25-775ba79140ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>72149e63-e8df-4530-99ec-fa2f139d6576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>refreshZone1();</value>
      <webElementGuid>2014a1fb-e2fd-4742-a57f-3c805ed7d520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bd7ab1b1-f4da-4540-a7fa-e31ebf5e0cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anTLZ1Refresh&quot;)</value>
      <webElementGuid>4a2bad8d-c123-448e-ac6e-0e11fe3d9113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anTLZ1Refresh']</value>
      <webElementGuid>6f9f1bbe-bfe8-4d02-8f8e-1d6f9791ba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='multiQueryFilterBody1']/tbody/tr[3]/td/input</value>
      <webElementGuid>44898fc9-f2a2-4b2b-a777-4a2b31b4f54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>b75f2361-ea46-4c2e-9c95-a15f0e1f6d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'anTLZ1Refresh' and @name = 'anTLZ1Refresh' and @type = 'button']</value>
      <webElementGuid>8881a3c3-a4b6-45bd-940d-0b50c749d8d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
