<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>codigoPais</name>
   <tag></tag>
   <elementGuidId>e4f67f23-a0de-4c34-9ec9-a7f11bc370f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter1.F1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac5838fb-670d-4045-80cb-747c90b93caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>439c063d-e821-46fd-8c44-c7e2168a15e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter1.F1</value>
      <webElementGuid>c3020b9f-3730-4c67-8f73-63c417ff8458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter1.F1</value>
      <webElementGuid>3cb6dbce-7097-4fe8-9f27-ecac8bf01841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>02d4e647-18fc-484b-81b1-4b8b1efb3a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>bee8f103-989c-40fe-b00e-1ac842f1891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>c4c21f3e-fdd8-4e3b-851c-7e4dc8aad4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d8918f43-f176-4d3d-b21d-6c425b6b0225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>dataExplorerKeyPress(event)</value>
      <webElementGuid>c598901d-e518-44e7-914a-f43bb70af3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>likeable</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>1f18660a-4ae7-4437-8c9f-8fc37fa9ed96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>dataExplorerTextBlur(event, document)</value>
      <webElementGuid>93398a08-3726-4e4b-ad54-85efd1c394a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter1.F1&quot;)</value>
      <webElementGuid>5c04bcf4-a12b-48b6-b4bb-403192d80e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter1.F1']</value>
      <webElementGuid>7ef6bcb8-38f2-433f-a8fd-d1f0b33cca16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='multiQueryFilterBody1']/tbody/tr/td[2]/input</value>
      <webElementGuid>a2d802a0-d87e-4eb6-9e3b-0a22bd632e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>eff8a083-d36e-4b42-a860-84ef63730a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filter1.F1' and @name = 'filter1.F1']</value>
      <webElementGuid>45d0d4d2-589a-4cd3-8d7d-cb65ea4a3ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
