<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pais</name>
   <tag></tag>
   <elementGuidId>5fa4ee89-644a-4540-9747-ca8e35e5b347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter1.F2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80b99c1-e5f6-4edb-a5b4-fcd6c27dfe77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa51b672-7151-4ce7-af6c-e835ffa9a8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter1.F2</value>
      <webElementGuid>6e9ef5a2-5c16-4d03-a7f6-e6b0a6c02bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter1.F2</value>
      <webElementGuid>2204097d-0036-4e15-80a1-57435698f31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1e8597a7-9dba-4910-9366-7af37fc02654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>62f29400-7365-433b-92d6-5ab82b901ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdatatype</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>8542b304-95ae-44c3-b04d-37b1cab71355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ba36178c-6295-4607-9982-b5468277fa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>dataExplorerKeyPress(event)</value>
      <webElementGuid>49f1c1c7-01e5-446d-9154-21e74b8c4878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>likeable</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>e56f6ba4-f616-42ce-b5e8-0fab983e7f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>dataExplorerTextBlur(event, document)</value>
      <webElementGuid>d68147da-9cc3-478e-b91b-944be9e1ce37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter1.F2&quot;)</value>
      <webElementGuid>0d16f2e9-c0d7-4138-8b4a-cad92beab46e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter1.F2']</value>
      <webElementGuid>3d5a3a42-ca48-43f7-a89f-7b5e3e97d3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='multiQueryFilterBody1']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>768f62cd-dab2-43e3-9d03-f10ca9a81b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>21f8c523-b91f-484d-873b-041271a15b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filter1.F2' and @name = 'filter1.F2']</value>
      <webElementGuid>5559cb07-11b5-4a07-9860-3f2ce86d4179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
