<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zoneMapFrame1</name>
   <tag></tag>
   <elementGuidId>096a1bb2-2d3e-4e43-8973-e2c58f1b3097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'zoneMapFrame_1' and @id = 'zoneMapFrame_1' and @class = 'zoneMapFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zoneMapFrame_1</value>
      <webElementGuid>3a868136-c509-4d56-a4c8-ffeea5273497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zoneMapFrame_1</value>
      <webElementGuid>59bdc356-56f3-44b4-87d5-3f35a4f14a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoneMapFrame</value>
      <webElementGuid>09de25b7-8dc4-4ee1-87fa-84aaff0b85a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_tabPage</value>
      <webElementGuid>e39e0438-97ce-48a2-8a75-a255d07e5c65</webElementGuid>
   </webElementProperties>
</WebElementEntity>
