<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cessarRegimeIVA</name>
   <tag></tag>
   <elementGuidId>cb739554-3a5c-4602-85da-1eac52443703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[contains(@id, &quot;vatRegimeEnd&quot;)]//input[contains(@id, &quot;boGroup_registrationDetails_vatRegimeEnd_asCurrent&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_registrationDetails_vatRegimeEnd_asCurrent</value>
      <webElementGuid>e45a0903-938d-408b-8470-c5c5cdf9c1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>7b1e8cc9-4d31-4e8c-8531-16b1f509e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onClick</name>
      <type>Main</type>
      <value>genericCheckBoxHandler('boGroup_registrationDetails_vatRegimeEnd_asCurrent',['boGroup_registrationDetails_vatRegimeStart_asCurrent']); handleIVAOperationCheckboxes();</value>
      <webElementGuid>b862719e-d1a6-461f-b328-cbf59efcf8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ee4ed1ee-5dd8-4e72-ab34-901f24d0faec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>display:;</value>
      <webElementGuid>3fffc8ae-848f-431a-ac7d-f9f788a37987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>763b7e8d-b3d0-403f-91ff-99c50594abd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/vatRegimeEnd/asCurrent</value>
      <webElementGuid>ac666058-0614-4f61-99e0-cf82a7045b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66b7f375-733e-4ccd-89a0-572d96305f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[contains(@id, &quot;vatRegimeEnd&quot;)]//input[contains(@id, &quot;boGroup_registrationDetails_vatRegimeEnd_asCurrent&quot;)]</value>
      <webElementGuid>9aeaab8a-9343-428d-b732-d1d84e6b564a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_VAT_REGIME_END</value>
      <webElementGuid>58cd7026-1474-447d-b0f0-1d5ed964902b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>eca728c3-30d8-4e1c-b99b-e0ba003a8b35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
