<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>residenteAusente</name>
   <tag></tag>
   <elementGuidId>334934b3-6e16-45e9-8653-2c56f4f4bf63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_registrationDetails_absentResident_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_registrationDetails_absentResident_asCurrent']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_registrationDetails_absentResident_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_ABSENT_RESIDENT' and @ref_element = 'Object Repository/teste/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f441b1b-49de-47ae-8526-90d952dbcc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ea09a280-b995-492f-aa84-ec60197eb483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/absentResident/asCurrent</value>
      <webElementGuid>7003b62f-04f7-4fbc-8891-023a9e02a730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ede3bc5c-4ea6-454f-81a2-3c5cf321ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>a0585d15-2820-4e4b-831d-da75214a21aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_registrationDetails_absentResident_asCurrent</value>
      <webElementGuid>4363b69e-d289-4c28-af36-f48d81b69109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ABSENT_RESIDENT</value>
      <webElementGuid>66ab48af-ce5c-4f1f-992b-ae4bc8730cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>781fad72-d0a3-49b2-877b-d56be181552e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/absentResident/asCurrent</value>
      <webElementGuid>1dfd6da0-472f-40ee-828f-62ce572293ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>55cc45e5-0247-47ea-853d-c4596df6e515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>459e4cae-cb18-4663-9d55-249625427393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_registrationDetails_absentResident_asCurrent&quot;)</value>
      <webElementGuid>7b7e25d2-4a87-4f06-ada7-65340cc69189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>46a59fa9-35d7-428b-aaf1-2323b888c356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_registrationDetails_absentResident_asCurrent']</value>
      <webElementGuid>dbdf3ef6-b2f5-407c-b8e7-ebc090827b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registrationDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>40b4b7c9-ad1e-4980-af11-33d4aa6472cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>4ee0052f-0ffa-4921-98ac-434f88305237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_registrationDetails_absentResident_asCurrent']</value>
      <webElementGuid>ce46ee37-ff72-4070-bda1-2b4e816c8b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
