<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simples</name>
   <tag></tag>
   <elementGuidId>73e50865-3328-46b1-9017-754878f78ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_registrationDetails_singularSimple_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_registrationDetails_singularSimple_asCurrent']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_registrationDetails_singularSimple_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_SING_SIMPLE' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e364435-614f-4e54-a61a-8c5ce422d46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>50894482-89e7-4d44-9717-c6bda4c7c3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/singularSimple/asCurrent</value>
      <webElementGuid>f135cd9c-9a5c-45be-87c2-a8de44d11a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3a94f17c-0138-4868-8d9e-ae8aebb089bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>506dbd27-9e90-4f40-905d-d491010a097b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_registrationDetails_singularSimple_asCurrent</value>
      <webElementGuid>1973434f-9f11-4015-9298-6f7164c34fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_SING_SIMPLE</value>
      <webElementGuid>1131de63-75bb-4169-bdce-3807e153d0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singularCheckbox oraDefault</value>
      <webElementGuid>5dd14c6a-efa8-441d-8041-7ffaeee8f127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>5313977e-4a6c-4195-ac2e-2ffee83d6a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/singularSimple/asCurrent</value>
      <webElementGuid>a3e7bca5-43a6-4bfb-b59a-e6557e2d11a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5f85432-c9ad-4ec3-a63b-3ac3540a4fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_registrationDetails_singularSimple_asCurrent&quot;)</value>
      <webElementGuid>af0b6fa2-bfa1-4cea-b41a-e6307b7b1177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>fb6f7ee3-a08c-495c-8e23-86664af638e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_registrationDetails_singularSimple_asCurrent']</value>
      <webElementGuid>8bee1130-086b-4f39-bbff-99efb4807a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registrationDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[16]/td[2]/input</value>
      <webElementGuid>646069e0-1197-4eb4-958b-d31e3c6e8540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/input</value>
      <webElementGuid>4bb84b18-3f04-4299-974b-b71f233a4c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_registrationDetails_singularSimple_asCurrent']</value>
      <webElementGuid>08fb0cbe-66f7-48e5-88bf-15e08ad4e286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
