<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>trabalhadorContaPropria</name>
   <tag></tag>
   <elementGuidId>1eaf56a4-0a88-401f-8123-c3a2f6f83404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_registrationDetails_singularOwnAccount_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_registrationDetails_singularOwnAccount_asCurrent']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_registrationDetails_singularOwnAccount_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_SING_OWN_ACC' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da316b8a-70ca-4ccc-a6db-91ceb0224042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>22a4ae46-58c8-4169-8b9e-a611fc4f97fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/singularOwnAccount/asCurrent</value>
      <webElementGuid>8a58b4f7-f347-4f99-b30e-1ede72a361ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>847cdbe3-06f2-46b9-ae69-4a82a442f5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>eafd44ae-f811-4fee-aa3e-c36d2f9fb851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_registrationDetails_singularOwnAccount_asCurrent</value>
      <webElementGuid>2d2de6aa-d171-495e-85a4-9ba49eb1891c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_SING_OWN_ACC</value>
      <webElementGuid>05732b2f-aac8-4ba4-9037-ba28deeb45f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singularCheckbox oraDefault</value>
      <webElementGuid>03e22642-ddf2-4a61-b989-500bf9cc0d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>99c96db4-48c4-4f85-9f01-cc52f000a58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/singularOwnAccount/asCurrent</value>
      <webElementGuid>d6a7cce4-e774-4b42-bc70-633c6d7c3694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc8dbdfe-934f-4aa7-b0c0-87670a79d12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_registrationDetails_singularOwnAccount_asCurrent&quot;)</value>
      <webElementGuid>9e89a789-eb28-4b10-b3b6-ede72b2ea166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>dfccdad5-2699-42a6-82ac-d7c05ebf4dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_registrationDetails_singularOwnAccount_asCurrent']</value>
      <webElementGuid>bb7537cb-4134-4b6b-abec-9f1c2f055cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registrationDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>e063a809-8802-4cc9-8f3b-0225615467b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/input</value>
      <webElementGuid>58945bd0-e89a-4d3d-85a7-ef43497b2762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_registrationDetails_singularOwnAccount_asCurrent']</value>
      <webElementGuid>39ed380d-2394-4415-bc65-ae6e6acb29db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
