<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>autonomia</name>
   <tag></tag>
   <elementGuidId>1e747b5b-f63c-44a0-8f3e-b03256e15eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_otherCollectiveDetails_autonomyType_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_AUTONOMY_TYPE_FLG' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Outros Detalhes do Contribuinte Colectivo/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_autonomyType_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boGroup_otherCollectiveDetails_autonomyType_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7a3b5fe-0cfe-43e5-8a43-43b6cd0b5df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a8f71b39-89ec-4ab5-98cd-f697537a3778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmAutonomyType oraDefault</value>
      <webElementGuid>fb3703f3-5017-45cb-a56c-847f09695f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>hideDropdownItem(this, 'cmAutonomyType', 'NA');</value>
      <webElementGuid>4cf75ff9-48f1-4439-b906-369baec36e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselect</name>
      <type>Main</type>
      <value>lookup:CM_AUTONOMY_TYPE_FLG;</value>
      <webElementGuid>9fc8d6a3-e9b5-4673-b904-4f4ed380d7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/autonomyTypeFlg/asCurrent</value>
      <webElementGuid>602f8c3a-6e82-408c-b72e-762646fc5aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>2bdab258-6880-4328-9fdd-5e4e99528adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_autonomyType_asCurrent</value>
      <webElementGuid>cf66e121-06e3-4760-b2cb-d6f0564d706d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_AUTONOMY_TYPE_FLG</value>
      <webElementGuid>1b368ce7-f560-4603-8dd1-be1781d8090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:4</value>
      <webElementGuid>d21af007-3e87-408e-979b-905726109a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>1bf1d8e3-452b-4fa3-82b5-9d22a298f88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/autonomyTypeFlg/asCurrent</value>
      <webElementGuid>11053f97-72c9-4a39-8edf-161b0b98cdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>


Orgão Dependente (OD)Unidade Orçamental (UO)</value>
      <webElementGuid>c718ffe5-4a56-4c63-932e-8c0efb889d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_autonomyType_asCurrent&quot;)</value>
      <webElementGuid>878040e2-3970-4ba7-a0ea-3c501150a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>139783a1-1300-4c56-8956-3cddf9ebb428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boGroup_otherCollectiveDetails_autonomyType_asCurrent']</value>
      <webElementGuid>a48910bb-f02b-4297-821c-b70839fa2f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[28]/td[2]/select</value>
      <webElementGuid>f9779937-ab8c-4997-9977-51982a01169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autonomia'])[1]/following::select[1]</value>
      <webElementGuid>386ee877-486b-465f-b055-c81e624e6197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fonte de Receitas'])[1]/following::select[2]</value>
      <webElementGuid>6f7ecd4b-8180-40e8-bd06-c2bcb0da6bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secção de Detalhes da Associação'])[1]/preceding::select[1]</value>
      <webElementGuid>99a17458-3b75-41c8-88c8-4e10ec709186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segmento'])[1]/preceding::select[1]</value>
      <webElementGuid>c9304638-08af-4e25-89ac-5dc2015c55be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[2]/select</value>
      <webElementGuid>ed1a2aed-0fb7-427d-8abe-f2528d7ae862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'asCurrent' and @id = 'boGroup_otherCollectiveDetails_autonomyType_asCurrent' and (text() = '


Orgão Dependente (OD)Unidade Orçamental (UO)' or . = '


Orgão Dependente (OD)Unidade Orçamental (UO)')]</value>
      <webElementGuid>9f51dc41-26e7-4d1e-8a8e-090972edb61e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
