<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dataPublicacaoDiarioRepublica</name>
   <tag></tag>
   <elementGuidId>08a55d90-90d6-4e20-bbb4-28f84e6611d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bf4fe3b-4695-497b-8c5e-a4dcad767514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>33710c7a-b80c-42e6-b213-be2abcd0fccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollDatePublishInGazette/asCurrent</value>
      <webElementGuid>4ad466a3-d620-4a1f-bb45-b46a92c4ba36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>ac234427-d19b-40a9-bd10-3c59fcf0ddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>e4ab3390-a604-4367-a0d9-e5f0fe93fcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>449503ab-9c26-41ab-a819-b56416bd8314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent</value>
      <webElementGuid>baff44e3-e346-4019-b142-245bff6798bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_DATE_PUB_GAZ</value>
      <webElementGuid>99166ace-88db-45a0-8b21-150b85a9a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>cb4fe26f-080c-4305-85ef-b0049ad7d7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollDatePublishInGazette/asCurrent</value>
      <webElementGuid>76354d01-46c5-46e1-a984-3815ca3c1ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDate</value>
      <webElementGuid>f116a566-9eb2-4790-a88b-3aff8a72599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oradatepickerexist</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10ea00ed-2c73-465a-ac4e-c44639c82122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent&quot;)</value>
      <webElementGuid>c7e16fa5-e9e9-4cbe-bab1-fc7084dfd974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>47c9c536-81b9-4093-b401-eff701a307c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent']</value>
      <webElementGuid>e3d3b0ba-d093-4115-b5b2-eab8d693e1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>f732e9f6-2509-49c5-8866-9b9ab629b975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>9a81ec5f-2ea3-45ae-b9fa-79650a1d9230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollDatePublishInGazette_asCurrent']</value>
      <webElementGuid>0e3c81c8-0095-46f1-aee6-d075ac7aa5df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
