<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailDoResponsavel</name>
   <tag></tag>
   <elementGuidId>34c7b0dc-80ae-4b3d-abaf-70f865094580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_asCurrent_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @type = 'text' and @id = 'email_asCurrent_0' and @ref_element = 'Object Repository/test/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_asCurrent_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dc9b26c-2592-44b0-ad0e-0074244f83f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1fa1805a-9a5e-4fd7-a804-60a304a5e075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this);</value>
      <webElementGuid>cca84b1c-ff69-4ed1-8bcd-89296d0eee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>email1/asCurrent</value>
      <webElementGuid>c10a40e6-8074-447b-aafc-f739ee1d07bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>14d2a8a9-68d9-45fd-bbd0-ddb8ae886616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>1a483c19-1653-4821-9fcc-4283e7602341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>789f0f43-594f-43ba-bc4b-966a176ce6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_asCurrent_0</value>
      <webElementGuid>6a99ece8-f9b0-42fd-93f6-688e84bc4c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_AC_EMAIL</value>
      <webElementGuid>693331c6-1146-4fc3-a2b0-b30056c3bfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:256</value>
      <webElementGuid>51bc66d1-68a0-4644-b475-ed101952dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>email1/asCurrent</value>
      <webElementGuid>95c248fa-7c9b-46be-a8bc-954e22600a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>1e32e75e-63cf-4b86-8276-39f5331f651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>86cb66f2-58e7-4867-ba94-d4d971c78ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>4becc159-e4d4-4405-bba5-152a9cb900cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>email_asCurrent</value>
      <webElementGuid>f21f1d04-3343-4c0e-8ed6-71fe2b1efc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>email_asCurrent</value>
      <webElementGuid>2cc97425-af90-484d-9fbb-b8b63036b292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollectiveDetailsHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[20]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@class=&quot;oraNormal&quot;]/td[2]/input[@id=&quot;email_asCurrent_0&quot;]</value>
      <webElementGuid>549b44aa-9a89-4121-9b18-37beb52b1c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>38f536dc-4a13-4f92-b904-229f54c8bd67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_asCurrent_0']</value>
      <webElementGuid>3c5bc9ea-2fbf-4994-8453-2264e71d0eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[20]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>baabd25f-f979-424b-98ce-6fe52c874ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>6cdcecfc-8352-423b-b61c-637be070b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'email_asCurrent_0']</value>
      <webElementGuid>44a2366b-027c-4067-acf0-19402b8d17d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
