<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>estrangeiro</name>
   <tag></tag>
   <elementGuidId>46b11889-3e90-47bc-81f7-d615560d75d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_otherCollForeign_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollForeign_asCurrent']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_otherCollectiveDetails_otherCollForeign_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06748c71-8e7f-4082-8f00-6d89eb293a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>220a8786-64a0-471b-8f9b-489ec68823d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleOtherCollectiveDistributionOfCapital();</value>
      <webElementGuid>08951645-055c-4645-90b8-a26a2635a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollForeign/asCurrent</value>
      <webElementGuid>0dfc4fa9-82ad-424f-b537-96eb6c55091f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>89c8dc61-b951-4297-a371-d1d29c18f500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>9399d05b-9686-4b6a-a790-c8e8f4d4e59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b887bb5d-ea23-4b34-aca0-795a3f750d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_otherCollForeign_asCurrent</value>
      <webElementGuid>178fe184-7592-48ce-a7f4-ba04dd409dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_FOREIGN</value>
      <webElementGuid>33a5b365-d486-4010-9421-4c06ea626f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>number;precision:5;scale:2</value>
      <webElementGuid>2a8e5612-9af0-4894-9e45-86933d07e1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollForeign/asCurrent</value>
      <webElementGuid>765790b3-8d39-4c71-9a3c-d7e8f0a6d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraNumber</value>
      <webElementGuid>4c1d2995-e816-4b48-841e-8134f226dda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>ce1383de-ae33-4382-be41-f47dec5a2c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>37f86c97-d025-419b-aeab-42bf7015daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_otherCollForeign_asCurrent&quot;)</value>
      <webElementGuid>a82a2b8b-a9ae-4fce-afe2-4afa112001c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>5301f4e9-e6f8-4c18-9470-ebf7bd4d4ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_otherCollectiveDetails_otherCollForeign_asCurrent']</value>
      <webElementGuid>2269e003-2699-4d01-aadb-df3d3bfbd29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>a183a915-4f4b-4b49-8bec-2a614de6714e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>12880f9b-d3f3-4b48-9e9f-dc5543f29763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollForeign_asCurrent']</value>
      <webElementGuid>0f9643e4-dadb-4a37-a63c-f6ac75f6977e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
