<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconeDePesquisaNIFOutrosResponsaveisOuGerentes</name>
   <tag></tag>
   <elementGuidId>55108a92-5315-4c98-baeb-27aff27bde72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherCollNIF_asCurrent_search_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollNIF_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para NIF' and @title = 'Pesquisar Para NIF']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='otherCollNIF_asCurrent_search_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec8197e1-516d-453c-bd46-b3ece97a111e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollNIF_asCurrent_search_0</value>
      <webElementGuid>8a59ae1a-5a13-47ef-9c5f-c10482a0ca62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1daa3eb6-7fe1-4aa9-ae57-33f8afc2b9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>a38109b4-bd66-4e5e-9d49-2b06dfd026d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>ef3a532e-11ca-416e-9f09-3c152383baaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para NIF</value>
      <webElementGuid>338dc0a3-fbd2-4efd-b974-9844e6840e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para NIF</value>
      <webElementGuid>7866b8e3-c40d-4f84-b112-8b5701301cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>ab6ec209-f998-4329-866c-f8e1d3374f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>89aacd8c-8e2c-4810-af44-ca8be5d7811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollNIF_asCurrent_search</value>
      <webElementGuid>6993aec8-6f71-49b1-aaa9-562953c8a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollNIF_asCurrent_search</value>
      <webElementGuid>7d9ff877-4b78-444c-ae22-5232ae4ade13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_otherCollNIF_asCurrent_search_boGroup_otherCollectiveDetails_otherCollManagementDetailGroup_otherCollManagementDetailGroupList</value>
      <webElementGuid>f4f60eb6-ce7e-4d67-ac9d-7155157321cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollNIF_asCurrent_search_0&quot;)</value>
      <webElementGuid>a13553b7-3dbf-45ce-9894-63f255c62d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>3204296d-380f-4046-94df-8fc476150979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='otherCollNIF_asCurrent_search_0']</value>
      <webElementGuid>c714cbb0-862b-4c70-8118-c3d497a4f136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[22]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>700c83db-511a-42dd-8fa9-27944b94bd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pesquisar Para NIF']</value>
      <webElementGuid>e07401bf-2c48-4085-bd11-56f25033d574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>6af68b83-b0ff-4150-8c7b-b5ea2daadcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'otherCollNIF_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para NIF' and @title = 'Pesquisar Para NIF']</value>
      <webElementGuid>425baf7c-676d-4764-8d2a-c637a845a965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
