<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lupaContactosDoResponsavelCodigoDoPais</name>
   <tag></tag>
   <elementGuidId>d869190f-5874-43ee-b649-466a519bf977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#othercol_phoneCode_asCurrent_search_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'othercol_phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='othercol_phoneCode_asCurrent_search_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c81e9f25-b742-4dbe-b365-211a956915dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search_0</value>
      <webElementGuid>71dcd233-4ecb-4c8f-b089-b7c447de67af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5984273f-930a-42a1-af46-25e7d6496445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>098d6afc-9d03-4750-a6ee-3bd11de00433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>7f3a7bc9-fb4f-422c-a584-6b925e14a0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>a3d1c36b-e30e-49ea-a1bc-5d2210599357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>35d793f7-0992-4595-9e27-a5c2a4225643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>0e827114-88c9-4ec0-91c3-d4761b29823f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>a0226cbc-c045-43e7-8558-2ebfc0ece39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search</value>
      <webElementGuid>1da3afac-66da-4a6f-91f2-045042b8f622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search</value>
      <webElementGuid>c0951d5b-0df7-4d70-8697-470abe2c3865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_othercol_phoneCode_asCurrent_search_boGroup_otherCollectiveDetails_phoneDetailsGroup_phoneDetailsGroupList</value>
      <webElementGuid>d850b2d7-205a-477b-9151-770dd9bc1001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollectiveDetailsHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[18]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@id=&quot;phone_country_Code_col&quot;]/td[2]/img[@id=&quot;othercol_phoneCode_asCurrent_search_0&quot;]</value>
      <webElementGuid>4e6a1d3e-1a7c-4563-9375-ec1834c0c258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>8a07542a-279e-4c5c-982b-2ac5d0e30b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='othercol_phoneCode_asCurrent_search_0']</value>
      <webElementGuid>e1cc3b6f-5343-41f7-b8bc-11e711c2d031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='phone_country_Code_col']/td[2]/img</value>
      <webElementGuid>86e258d2-aac8-4ef9-967a-0213e31d68dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pesquisar Para Código do País']</value>
      <webElementGuid>71b4190c-172f-40f2-a59b-3a41a29a4c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[4]/td[2]/img</value>
      <webElementGuid>29f3c02f-7d76-4e23-8128-bffe4ec31bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'othercol_phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      <webElementGuid>004d31fe-0e2a-410f-b3a0-272f9b0c6966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
