<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lupaRepresentanteLegalCodigoDoPais</name>
   <tag></tag>
   <elementGuidId>7122891e-9225-4aa5-bfdc-cb3bca44052e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_legalRepresentativeGroup > td > table > tbody > tr > td > table.layoutSectionTable > tbody > tr > td:nth-of-type(3) > table[name=&quot;listParent&quot;] > tbody > #phone_country_Code_col > td:nth-of-type(2) > #othercol_phoneCode_asCurrent_search_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@id=&quot;phone_country_Code_col&quot;]/td[2]/img[@id=&quot;othercol_phoneCode_asCurrent_search_0&quot;][count(. | //*[@id = 'othercol_phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']) = count(//*[@id = 'othercol_phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='othercol_phoneCode_asCurrent_search_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbd1a413-0bb1-4e66-b561-800ba86d8594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search_0</value>
      <webElementGuid>d7c063a4-035c-4314-84f8-f18bf447c5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7a361563-8914-4a0a-9ab3-39ab1e21b787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>a2b2797a-c15d-4100-8aef-3b2f1afdc68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>2f79619f-17fe-4871-8f47-90a60bc8f43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>07e0b9e3-cf7e-4911-a1af-cd167f5c1b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>6ba8e0a7-c38d-491e-98ea-0577b0459fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>f07f590a-d84d-4d78-9ada-7fef42a007aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>4b49d75e-da2d-4e21-b801-9d6c597e4fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search</value>
      <webElementGuid>a2995f2c-27be-41c8-af5a-873ac97d9eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>othercol_phoneCode_asCurrent_search</value>
      <webElementGuid>db722086-06ea-4a92-acc4-5ae00dd3c6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_othercol_phoneCode_asCurrent_search_boGroup_otherCollectiveDetails_legalRepresentativeGroup_legalRepresentativeGroupList</value>
      <webElementGuid>a8f9be33-4995-4c01-90f8-bd042e14687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@id=&quot;phone_country_Code_col&quot;]/td[2]/img[@id=&quot;othercol_phoneCode_asCurrent_search_0&quot;]</value>
      <webElementGuid>6444e14b-365b-4eb2-8812-56dbb24e4cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>4af29004-e072-47bf-8e5a-10ac5bf4dc0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='othercol_phoneCode_asCurrent_search_0'])[2]</value>
      <webElementGuid>f9572d34-ad12-4d19-82d0-38cb5d31cfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='phone_country_Code_col']/td[2]/img)[2]</value>
      <webElementGuid>92361c43-c820-4ed5-bdad-9bd2f483dad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Pesquisar Para Código do País'])[2]</value>
      <webElementGuid>f31f1111-92cb-4e3f-bd2d-dcec898d72c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/img</value>
      <webElementGuid>aa8baf95-9fe1-483f-85c3-916f0844a41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'othercol_phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      <webElementGuid>a9795c56-35ff-4112-8f1f-8db7bb857533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
