<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lupaRepresentanteLegalNif</name>
   <tag></tag>
   <elementGuidId>6d45c05b-b51b-439c-9e43-cf334f3971c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0' and @src = 'images/alta/search.png' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0dad9516-cff9-45c3-b5e8-11d7fea72048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0</value>
      <webElementGuid>ed47d081-cc2e-435d-97d7-2f61631d44d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d94f5960-fc5d-4d6d-ae7f-96c061f5f9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>1c0ee48e-0f3f-412a-bb79-156e8a3bd9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>dfbfe798-98ca-434c-8d94-7bae5efc243b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para NIF</value>
      <webElementGuid>db3c75c4-d27f-4815-91b8-ad7d47c54c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para NIF</value>
      <webElementGuid>6a3cb4aa-2e69-4615-8b34-b2b018042da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>530484db-b5c2-4307-9b99-91104a666fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>e1fa1c5b-b479-4af4-99e0-7c0c0e1722ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_representativeNif_asCurrent_search</value>
      <webElementGuid>0c5491eb-8d62-4d33-bb3c-cb7e4542b9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_representativeNif_asCurrent_search</value>
      <webElementGuid>134b5d80-ad1d-4831-9069-8e6bf105000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_boGroup_otherCollectiveDetails_legalRepresentativeGroup_legalRepresentativeGroupList</value>
      <webElementGuid>682c6b9a-8c35-4875-a9b7-ffe8ba30f6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0&quot;)</value>
      <webElementGuid>5a845c6a-06a8-4ec9-a1f7-2ae440ef9bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>bc12c45b-6295-4719-90c4-b6c921300e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0']</value>
      <webElementGuid>5dbc4246-6d7c-48d9-adf8-710889325614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='boGroup_otherCollectiveDetails_legalRepresentativeGroup']/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>74663e7d-8fda-484c-942c-4505c35ba184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Pesquisar Para NIF'])[2]</value>
      <webElementGuid>a8b12a40-bd64-4729-bc55-ab85f5c21cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>61fa37be-e7af-47a1-bb4e-b54085668797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'boGroup_otherCollectiveDetails_representativeNif_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para NIF' and @title = 'Pesquisar Para NIF']</value>
      <webElementGuid>22911e7e-a347-4ca8-a6c1-70c430331a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
