<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nTrabalhadores</name>
   <tag></tag>
   <elementGuidId>f10fe44a-6b51-4db2-bd80-25f3083b29d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d215372-0358-4541-a839-42c1568143bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault oraNumber</value>
      <webElementGuid>14421b86-907a-4509-b755-0ac5bf12845f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>656ec307-fbdc-4b32-b862-2c792bf67ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollNumberOfEmployees/asCurrent</value>
      <webElementGuid>bc7b0d4d-ceca-4e10-ab35-21b1046cd927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>1d8b3ed9-66e5-4ae2-b305-a70abaf0c379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>eafaba23-b064-4931-b2fb-afcb45b5b6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8a042ab-0226-4d21-a7cb-22fd46415c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent</value>
      <webElementGuid>f1528a0d-219a-4ba5-a8de-d574fbf1d8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_NUM_EMP</value>
      <webElementGuid>53775db6-caa4-4f81-ada1-9ed4f8c18c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>number;precision:6;scale:0</value>
      <webElementGuid>c6c90297-8ff1-4f7b-b586-c7b0091e600a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/otherCollectiveDetails/otherCollNumberOfEmployees/asCurrent</value>
      <webElementGuid>e6b21111-62b8-4df2-8beb-c0b292d70794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>63b49101-743f-42ef-b5ea-ed9d8baa910c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>81c61e4f-430f-4406-a9dc-04c053be01d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent&quot;)</value>
      <webElementGuid>ed1d2386-83c2-4712-aaed-44e66413d12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>ce156849-a9c4-4b3d-8f67-c20c9666051d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent']</value>
      <webElementGuid>d0b7dd08-84a6-4d32-874c-07943cda3a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>8f9a13f5-1105-4ade-954a-e2b3627a86de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>6d830c07-aebf-424d-bff3-deb990aea80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_otherCollectiveDetails_otherCollNumberOfEmployees_asCurrent']</value>
      <webElementGuid>d130f7f9-7535-482b-be3e-a990982db5e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
