<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pessoaResponsavelIconePesquisaNIF</name>
   <tag></tag>
   <elementGuidId>ceb114e5-3064-4456-b96b-2d96092e12bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Pessoa Responsável (NIF)' and @title = 'Pesquisar Para Pessoa Responsável (NIF)']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d81f5ce-b13b-49d5-96d2-f828105947a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search</value>
      <webElementGuid>2d40a5bd-38ad-4a50-b96d-691e0b6f5c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>befee14b-d9b6-4461-9e04-e4860116ac4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>1bbf2f38-39ab-4316-9ed2-aba6b55924ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>2039564d-07ca-4144-9386-112483d5c5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Pessoa Responsável (NIF)</value>
      <webElementGuid>45fe6795-678c-4ff7-9b6a-1d0fab15752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Pessoa Responsável (NIF)</value>
      <webElementGuid>e0103fb8-f3b0-443a-9d93-420ef3b68acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>a0a800bb-342c-4ffe-b8f5-3419585f3483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>26543b82-b341-4261-bd05-0b79c2feff0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search&quot;)</value>
      <webElementGuid>100aafff-f5c6-4490-bd6e-1718df9b5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>cb4598a1-8d7e-48f0-8852-be93cd7dc332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search']</value>
      <webElementGuid>0e4b3da4-7338-4c83-8d0c-063980fbe0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otherCollectiveDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[14]/td[2]/img</value>
      <webElementGuid>708ca052-541e-43c5-acb8-13f004b92f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pesquisar Para Pessoa Responsável (NIF)']</value>
      <webElementGuid>08030906-3e6d-440a-b355-6cc58a1ed925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/img</value>
      <webElementGuid>a6311684-71b0-4fef-a830-e672ae5f1495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'boGroup_otherCollectiveDetails_otherCollRespInRegarTheFirmNIF_asCurrent_search' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Pessoa Responsável (NIF)' and @title = 'Pesquisar Para Pessoa Responsável (NIF)']</value>
      <webElementGuid>c7c387f7-f806-4d40-b120-d8b9e5b7f368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
