<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>representanteLegalEmail</name>
   <tag></tag>
   <elementGuidId>7845c67f-effc-4df1-874a-681438a24fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_legalRepresentativeGroup > td > table > tbody > tr > td > table.layoutSectionTable > tbody > tr > td:nth-of-type(3) > table[name=&quot;listParent&quot;] > tbody > tr.oraNormal > td:nth-of-type(2) > #email_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@orafield = 'email/asCurrent' and @name = 'asCurrent' and @id = 'email_asCurrent_0' and @class = 'oraDefault' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='email_asCurrent_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09dd1dc2-c9ff-4d83-b24e-dd3ff0a5d065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>38f834bc-eec0-4202-88a0-c38122abe81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this); otherColLegalRepMarkRequired();</value>
      <webElementGuid>d3af8416-3b59-4b24-bb4b-542911c47e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>email/asCurrent</value>
      <webElementGuid>b898f15f-8d37-4eb0-b16b-b5b24fa663ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>afa5da05-ab82-4368-b965-3168c416e740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>38c75b2a-adb3-4ae5-8255-52ce955e226f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bec9db55-86a0-4c03-9af3-beb4855854d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_asCurrent_0</value>
      <webElementGuid>14894adc-b643-4041-a97e-489391a793fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_AC_EMAIL</value>
      <webElementGuid>69ceb196-7879-4586-a026-9a41d11d113e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:256</value>
      <webElementGuid>04e7a981-fb7a-4a6d-bef1-de75fbbb305f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>email/asCurrent</value>
      <webElementGuid>d460ccd6-14f9-4d9a-b5c7-c0ed1eee01db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>ebf1ebeb-35ab-4750-a7cd-19000706574d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>88fcd416-cba0-4678-bf13-67e1de769d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>235fa4e1-240a-4bb0-86ee-183aa9d2f380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>email_asCurrent</value>
      <webElementGuid>b3894ca6-e97b-4520-96f2-5e9b6adc5588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>email_asCurrent</value>
      <webElementGuid>7c76540f-2dc0-4cb3-91a3-0a640fc8bd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@class=&quot;oraNormal&quot;]/td[2]/input[@id=&quot;email_asCurrent_0&quot;]</value>
      <webElementGuid>12eaf8f5-deeb-416b-936f-f37f31edd21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>9f752e75-0ee5-4de3-afc3-3fd5649e044a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='email_asCurrent_0'])[2]</value>
      <webElementGuid>6978f38e-a7c6-4723-8c6b-b3fdbcef3636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='boGroup_otherCollectiveDetails_legalRepresentativeGroup']/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>a2c8ee74-3f88-409c-87c1-26fdcb1fb5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>19bbbd2b-6089-4cf2-bead-fb8ac4c63023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'email_asCurrent_0']</value>
      <webElementGuid>8107134a-d694-414b-ab58-566dd2541c9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
