<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>representanteLegalTipoDeContacto</name>
   <tag></tag>
   <elementGuidId>f898d374-5a61-4449-8c97-f1e62e758b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_legalRepresentativeGroup > td > table > tbody > tr > td > table.layoutSectionTable > tbody > tr > td:nth-of-type(3) > table[name=&quot;listParent&quot;] > tbody > tr.oraNormal > td:nth-of-type(2) > #phoneType_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'phoneType oraDefault' and @orafield = 'phoneType/asCurrent' and @name = 'asCurrent' and @id = 'phoneType_asCurrent_0' and @ref_element = 'Object Repository/test/test1/New Folder/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='phoneType_asCurrent_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa546908-6df9-4199-bc04-251478d0940b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phoneType oraDefault</value>
      <webElementGuid>e9f3e0f3-b49b-4803-8072-203a70637db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b500d8c5-b64d-4230-a740-a7c73be1f745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>hideDropdownItem(this, 'phoneType', 'NA');</value>
      <webElementGuid>d5e408b1-3aa7-4f2c-b9e6-7c50e372acea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this); phoneTypehandler(this); otherColLegalRepMarkRequired();</value>
      <webElementGuid>0415249d-0e36-4470-be7b-f3c9e2e50a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselect</name>
      <type>Main</type>
      <value>table:CI_PHONE_TYPE</value>
      <webElementGuid>0dbea598-4b97-46f6-8918-8fd089bf2989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>phoneType/asCurrent</value>
      <webElementGuid>c5017aa8-e509-4b12-b314-c93af451e12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>fe915f12-da20-498c-8789-c403b208a421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneType_asCurrent_0</value>
      <webElementGuid>ef7d336d-b718-4a53-801d-1b7b03580773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_PHONE_TYPE</value>
      <webElementGuid>79508b87-1e6f-420a-bdde-ea35fecbc95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:1</value>
      <webElementGuid>d4d11f29-10e8-4c54-9ebe-fcf6fbb4dd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>8d06ca13-19c0-4508-9335-0f4c680d5902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>phoneType/asCurrent</value>
      <webElementGuid>39bdf626-f5f5-4876-8f71-84d8a0bb1cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>phoneType_asCurrent</value>
      <webElementGuid>da4d95f5-7c04-43db-9730-8e991af2003b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>phoneType_asCurrent</value>
      <webElementGuid>f2906e21-7433-4cfc-94b1-adeae1198864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>


EstrangeiroFixoTelemóvel</value>
      <webElementGuid>4018630c-30b0-48f2-a61f-9481a47d216e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@class=&quot;oraNormal&quot;]/td[2]/select[@id=&quot;phoneType_asCurrent_0&quot;]</value>
      <webElementGuid>ec3c165b-96ed-49d5-b524-203e66463648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>a9a782c1-087e-4adf-8d4f-932ab54186bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='phoneType_asCurrent_0'])[2]</value>
      <webElementGuid>eebef72a-7f03-4430-9ec6-c29af53d1ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='boGroup_otherCollectiveDetails_legalRepresentativeGroup']/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>207d0be8-8a8a-44f0-8b94-1bf0d2d073b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Contacto'])[2]/following::select[1]</value>
      <webElementGuid>824761e0-404e-4c6c-8207-dae0b7183aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Responsabilidade'])[3]/following::select[2]</value>
      <webElementGuid>4ce8393c-24ce-4df2-b3d7-5f3bb5023319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código do País'])[2]/preceding::select[1]</value>
      <webElementGuid>03af4c0a-68b6-4f18-8dc2-7be773d63ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[2]/preceding::select[1]</value>
      <webElementGuid>09ca048e-dbc8-40a9-abc2-a3809c5237a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/select</value>
      <webElementGuid>8e071fa3-4c4c-46cb-86fe-2bd38fed0218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'asCurrent' and @id = 'phoneType_asCurrent_0' and (text() = '


EstrangeiroFixoTelemóvel' or . = '


EstrangeiroFixoTelemóvel')]</value>
      <webElementGuid>43a25516-9f9e-45e3-a4fc-963d7c1a3e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
