<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>representanteLegalNumero</name>
   <tag></tag>
   <elementGuidId>60122605-f406-405c-b3f9-fd2e63430b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boGroup_otherCollectiveDetails_legalRepresentativeGroup > td > table > tbody > tr > td > table.layoutSectionTable > tbody > tr > td:nth-of-type(3) > table[name=&quot;listParent&quot;] > tbody > tr.oraNormal > td:nth-of-type(2) > #phoneNumber_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@class=&quot;oraNormal&quot;]/td[2]/input[@id=&quot;phoneNumber_asCurrent_0&quot;][count(. | //*[@name = 'asCurrent' and @type = 'text' and @id = 'phoneNumber_asCurrent_0']) = count(//*[@name = 'asCurrent' and @type = 'text' and @id = 'phoneNumber_asCurrent_0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='phoneNumber_asCurrent_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a8fee4-9eb1-4d10-91b0-e00a3c2b6378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>160d208a-43a5-48b2-8bb4-0fe6f56d959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this); otherColLegalRepMarkRequired();</value>
      <webElementGuid>67063a6b-358b-4ff0-9c0d-47004fef1053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>phoneNumber/asCurrent</value>
      <webElementGuid>41b59565-98f3-41c8-9141-9a90423e31f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>fda699d1-bf6f-43ec-8854-a8188d27ed36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>d77333aa-4b4c-4153-bda2-c7dbd2aa4dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>747b2ad7-1fe1-4a6e-8896-effc3c8a4527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumber_asCurrent_0</value>
      <webElementGuid>9cff70c2-d9c7-4e3c-b495-325137bb73ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_PHONE_NUM</value>
      <webElementGuid>87c2e51c-98c7-44d1-8466-60847a8f5464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:14</value>
      <webElementGuid>dc17ac56-8398-4567-ae53-88efe2d448ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>phoneNumber/asCurrent</value>
      <webElementGuid>86973982-0e12-4bd6-9f31-07241d0c1ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>9b0e8e08-2c6c-4a53-ac58-005a144b358b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>6a19f7e7-84d0-4017-b9e9-fe4c77b0165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8a4b5d97-38c6-4003-8051-a81559521f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>phoneNumber_asCurrent</value>
      <webElementGuid>94e595e8-ee7f-4e6d-b0d3-99088e5d3c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>phoneNumber_asCurrent</value>
      <webElementGuid>9660f150-af9a-44ba-a50d-b728e84ee5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_otherCollectiveDetails_legalRepresentativeGroup&quot;)/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[@class=&quot;oraNormal&quot;]/td[2]/input[@id=&quot;phoneNumber_asCurrent_0&quot;]</value>
      <webElementGuid>dfb16fd4-41df-4397-97a5-24fe28bb2c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>2b303f09-cde0-43b0-92ca-b16c3c2720bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='phoneNumber_asCurrent_0'])[2]</value>
      <webElementGuid>3ee38330-06d2-4dd3-a9db-b0a3ab15a07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='boGroup_otherCollectiveDetails_legalRepresentativeGroup']/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>feaf921d-6fab-4b72-be13-3d7c26c126d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>01f80abb-4334-46ec-816f-086b59f1c311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'phoneNumber_asCurrent_0']</value>
      <webElementGuid>ed683bd1-98df-4ee1-a978-74d24ede58cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
