<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>andar</name>
   <tag></tag>
   <elementGuidId>1fbbe90b-cc12-4d53-acce-00e7ec218d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_addressInformation_floor_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_addressInformation_floor_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_addressInformation_floor_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_FLOOR' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de endereco/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6205036b-3be1-4904-aa74-86a4e153c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e54ae9e7-27b8-4341-90a2-f1d99391fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/addressInformation/floor/asCurrent</value>
      <webElementGuid>bd2e537a-034f-4206-a688-8ae7d8a7125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>3772dee8-1974-454b-a341-439321dca998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>6b404045-92b0-4d9a-b7c9-6110c98e782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db32e72c-7c00-47f0-9278-d46d8d67ac1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_addressInformation_floor_asCurrent</value>
      <webElementGuid>f37ca139-b4a9-48b7-b169-e1eeedd6b1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_FLOOR</value>
      <webElementGuid>ecb05cba-ab9d-4111-92c7-dc486ca6f99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:254</value>
      <webElementGuid>736ae5f2-e82e-4ffd-86bd-f0fad39e30c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/addressInformation/floor/asCurrent</value>
      <webElementGuid>d38993cc-1eeb-4e36-90c8-0a92e389154f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>beb4e822-680c-4ac7-aa78-1e999514be4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>7431414f-39da-465b-8d37-2f1a3a81070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>767edac0-18f3-42ab-b38a-a478d8ecfad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_addressInformation_floor_asCurrent&quot;)</value>
      <webElementGuid>369b0b59-2cdc-404d-bfa2-bf7c3cb2ee24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>1fbd02e1-08d9-4e4f-8028-f6f4a3093ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_addressInformation_floor_asCurrent']</value>
      <webElementGuid>06ef4be8-7765-4b09-ad08-c49c83bc3bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[15]/td[2]/input</value>
      <webElementGuid>999a8b80-4013-4d0b-a370-9135c1622d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[15]/td[2]/input</value>
      <webElementGuid>d39db6d8-2b7e-43b6-b5b4-af948748321f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_addressInformation_floor_asCurrent']</value>
      <webElementGuid>b8e82c40-f5eb-406c-b380-d38ba4b751de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
