<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>comuna</name>
   <tag></tag>
   <elementGuidId>4a29515b-7ffd-47f2-9f50-22ce5ea32c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boGroup_select_addressInformation_addressCommune_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_select_addressInformation_addressCommune_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_select_addressInformation_addressCommune_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_COMMUNE' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de endereco/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3a0e920-64fa-485a-ba93-0f78297f2fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>communeSelector</value>
      <webElementGuid>360f3ee3-9630-4d18-80dc-f9ad517369eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>de59f114-5fa5-43d6-ad97-3e0df31a5184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_select_addressInformation_addressCommune_asCurrent</value>
      <webElementGuid>23684c6e-1566-421d-b44f-04eab724dfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('COMM', this);</value>
      <webElementGuid>c703ba38-2e25-40e9-99a6-e0ad384129e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fece68cc-e3ec-47e7-9a1f-9ae590e53e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_COMMUNE</value>
      <webElementGuid>bbe40b4d-fcf5-4776-97b9-16b18171e90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>cd7cd0f4-5b51-4651-a031-c027f9e36285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBRIZBELA VISTATABI</value>
      <webElementGuid>0fd14482-65f9-4c53-9542-ece31d0e0b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_select_addressInformation_addressCommune_asCurrent&quot;)</value>
      <webElementGuid>7523beea-f151-42a9-ab33-1b26d85cc4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>ad269d67-dc0f-425e-b35c-3bd9fb7d8058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boGroup_select_addressInformation_addressCommune_asCurrent']</value>
      <webElementGuid>872ac987-edd0-4f39-8757-2bbe0aaec1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[7]/td[2]/select</value>
      <webElementGuid>f4049c07-8774-410f-9f3f-88ed7adc92b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[2]/following::select[1]</value>
      <webElementGuid>a64d5af6-b3c4-443b-9908-0c421374d06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[4]/following::select[2]</value>
      <webElementGuid>975f8f7c-14d6-4360-8bed-fb760a2ae39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localidade'])[1]/preceding::select[1]</value>
      <webElementGuid>7576bb34-be7a-4f88-bb16-d14aff4cc3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bairro'])[1]/preceding::select[1]</value>
      <webElementGuid>9d8f57d5-a7f9-40ee-841d-f1e1b8810820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[7]/td[2]/select</value>
      <webElementGuid>89421810-5dd3-487c-a11c-40a9d4ab3020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'boGroup_select_addressInformation_addressCommune_asCurrent' and @type = 'text' and (text() = 'AMBRIZBELA VISTATABI' or . = 'AMBRIZBELA VISTATABI')]</value>
      <webElementGuid>9a6d2505-20fe-40c6-a4ef-12dc568cce29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
