<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edificio</name>
   <tag></tag>
   <elementGuidId>e28da0dd-007c-4212-a6cb-389526556505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_addressInformation_building_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_addressInformation_building_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_addressInformation_building_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_BIULDING' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de endereco/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e9da60c-40c9-4e29-b4a1-1b46678c2749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>367f7b4e-a080-4508-a170-5c184555c27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/addressInformation/building/asCurrent</value>
      <webElementGuid>6506dc08-748d-423b-a0e0-45fd1c15ce49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>ba07932f-a475-483f-bb8e-4ee67d62615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>ece98b16-54f3-402e-b5db-6c7f68beda56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50fbff61-4ce3-4318-89a7-2933e815539e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_addressInformation_building_asCurrent</value>
      <webElementGuid>a32db15d-6008-41fb-a2f9-8e70b7646a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_BIULDING</value>
      <webElementGuid>84d80228-0393-4a76-a8ca-765e8d439fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:254</value>
      <webElementGuid>e87930d8-a7a0-404e-b531-f8801d031481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/addressInformation/building/asCurrent</value>
      <webElementGuid>eb2dd2ee-fcc0-4609-816b-495298b3896b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>dd0ee149-eb7f-499b-a15d-a4b61066f2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>fffb564e-0cd5-4b2c-944a-70b11e218c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>80030251-e139-48c8-be71-09aeb728b847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_addressInformation_building_asCurrent&quot;)</value>
      <webElementGuid>cb3e640c-fb1c-4039-ac12-e1360cde661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>ba0f5a56-150e-46b7-afdb-6733b91ea584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_addressInformation_building_asCurrent']</value>
      <webElementGuid>860dabfc-55dc-48e3-a7a6-3cfb3f8965a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>3ee861ff-e2dc-4046-be3c-8deee280a9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>1feb54db-39c0-4fec-87b3-dc1922c81366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_addressInformation_building_asCurrent']</value>
      <webElementGuid>bc8d9ed8-1458-4e50-89ac-c3bf7986fcd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
