<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>municipio</name>
   <tag></tag>
   <elementGuidId>8e6c455a-1d1e-4c6b-92f9-a7e060aacec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boGroup_select_addressInformation_addressMunicipality_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_select_addressInformation_addressMunicipality_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_select_addressInformation_addressMunicipality_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_MUNICIPALITY' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de endereco/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>84827c10-33be-4299-af59-6b07241ec874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>municipalitySelector</value>
      <webElementGuid>b0d73ba5-4702-456b-a17f-5872bd2f2c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fcae2f99-facf-44c0-90c8-551722155ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_select_addressInformation_addressMunicipality_asCurrent</value>
      <webElementGuid>75834ada-f2cb-4cad-b593-203b577b9bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('MUNI', this);</value>
      <webElementGuid>46ea9f43-612d-4dbf-9de1-67e18be01f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3b70a23-3e86-48de-88d9-905efd760f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_MUNICIPALITY</value>
      <webElementGuid>4a5b20e3-145b-4160-960e-14f84927c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>bdf3e7a8-3026-4207-9ef1-f6d18a78044d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM</value>
      <webElementGuid>9f62c47d-a1a6-4ed1-accf-392a3f33ed75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_select_addressInformation_addressMunicipality_asCurrent&quot;)</value>
      <webElementGuid>b3bd1a72-ddf3-4095-944a-52bbb2b7fa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>3f7052b3-874b-4f24-bf11-0e888dc69dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boGroup_select_addressInformation_addressMunicipality_asCurrent']</value>
      <webElementGuid>bf473b33-0b94-44af-8f4b-9ca57c411af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>9c2230a3-3077-43ba-ba05-9e5ecf539db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[4]/following::select[1]</value>
      <webElementGuid>fcaed8f1-d6e7-427d-87d4-5f9f13db5433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[2]/following::select[1]</value>
      <webElementGuid>886a4326-fafd-4d6b-8dc7-0551b085e831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[2]/preceding::select[1]</value>
      <webElementGuid>98c1256b-c930-4093-8a99-f175e0a025ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localidade'])[1]/preceding::select[2]</value>
      <webElementGuid>7f99d0f6-df88-4aa8-bc14-865a11a3ed28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>17ef0688-095a-487e-b815-4e1507e02de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'boGroup_select_addressInformation_addressMunicipality_asCurrent' and @type = 'text' and (text() = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM' or . = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM')]</value>
      <webElementGuid>0bba4829-1db4-44e5-b28b-3812072be01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
