<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>observacoes</name>
   <tag></tag>
   <elementGuidId>5b0c9674-debb-422a-b5f9-f64c2dadcc19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='boGroup_registrationDetails_comments_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_registrationDetails_comments_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_registrationDetails_comments_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT COMMENTS' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de endereco/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>05a5fab6-0a3e-4680-8190-3e09ec556a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a4551a57-588d-4e65-a975-71bfce1a596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/comments/asCurrent</value>
      <webElementGuid>5d127d74-8c6c-4641-8529-e25afee440da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>0efaa88a-9635-4559-b04a-b3513db04249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_registrationDetails_comments_asCurrent</value>
      <webElementGuid>a2815b72-4c46-4a6b-b601-fa2274b42601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>ea391751-e81d-4a17-a715-02ac069fa2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3c1f67ae-954e-48d4-9b97-7fefb459ba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT COMMENTS</value>
      <webElementGuid>7ef0aff6-de1a-4526-8ea0-d73d601f40ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:254</value>
      <webElementGuid>0b35d271-4bc4-4d63-8699-fefa156aed4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/registrationDetails/comments/asCurrent</value>
      <webElementGuid>110f4aa6-1810-4bc8-a5e1-582e963ffb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>1482950e-288e-454e-88b3-22282370a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_registrationDetails_comments_asCurrent&quot;)</value>
      <webElementGuid>14bf9da0-16a3-4418-a43b-6708ef6f60ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>a0e140b4-46a9-4f87-b0da-1322f3bac05e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='boGroup_registrationDetails_comments_asCurrent']</value>
      <webElementGuid>98cbc422-8f4a-4d78-886a-a668ed2237b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[19]/td[2]/textarea</value>
      <webElementGuid>1e39fe5c-361f-4c4f-9c37-c011cb0937f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/textarea</value>
      <webElementGuid>c49d421f-d46c-4a1e-aa73-2515a47cb521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'asCurrent' and @id = 'boGroup_registrationDetails_comments_asCurrent']</value>
      <webElementGuid>b4a2f45d-8cba-4efb-aaaf-3b797b793716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
