<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>provincia</name>
   <tag></tag>
   <elementGuidId>4e3345e9-4f30-436e-8291-2de1a425710f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boGroup_select_addressInformation_addressProvince_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_select_addressInformation_addressProvince_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_select_addressInformation_addressProvince_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_PROVINCE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14f2f0cc-bbe6-4ec6-b635-d856447dbb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>provinceSelector</value>
      <webElementGuid>1511d79a-e5ea-4db1-8c70-89d1c5cccbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ec50d1ca-5eb2-47b2-879b-e976b1dfa9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_select_addressInformation_addressProvince_asCurrent</value>
      <webElementGuid>271c263b-e86b-435c-9781-b51988bd75ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('PROV', this);</value>
      <webElementGuid>0bc13dc4-302b-4897-a63f-b69e872a2074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97d6de34-5a7c-44c4-98ea-cd0253feb4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_PROVINCE</value>
      <webElementGuid>5d650995-22a1-4dbb-a7b6-5a62d517b5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>75c22002-2ba8-4d6a-aed9-c616d2d0e4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE</value>
      <webElementGuid>36798da8-1bc8-435d-9bf7-b61d06039c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_select_addressInformation_addressProvince_asCurrent&quot;)</value>
      <webElementGuid>2b345c69-05fa-4791-950e-32b1f7f0c93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>1f9c8cce-11dc-466b-8cff-ea20105d867f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boGroup_select_addressInformation_addressProvince_asCurrent']</value>
      <webElementGuid>2fea938e-3c0e-43ab-91cc-54bf7c83ef7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>d5729653-6f93-4c9e-9715-64b5c24d41a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Província'])[4]/following::select[1]</value>
      <webElementGuid>a95f583e-7f6a-4d5f-bb76-6cca8f1e5f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalhes do Endereço Diplomático/Representação Consular'])[1]/following::select[1]</value>
      <webElementGuid>3b4bd8cd-8b26-4f39-aa1a-6a006ec7c70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[2]/preceding::select[1]</value>
      <webElementGuid>c367b49c-3213-47ed-8a3a-2ccd138fe7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[4]/preceding::select[1]</value>
      <webElementGuid>f2b218c4-174a-4acc-ba0b-6b6b85df8466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>c13f2a7e-98a9-4d82-9bde-4fcb66a683f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'boGroup_select_addressInformation_addressProvince_asCurrent' and @type = 'text' and (text() = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE' or . = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE')]</value>
      <webElementGuid>dc5fe05d-2deb-43ee-974e-dfeef6cbe88c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
