<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>raparticaoFiscal</name>
   <tag></tag>
   <elementGuidId>a77c101e-b71d-4ac5-90e0-cc56fb4cdf5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_ADDR_TAX_OFFI_DOM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>75829b87-6619-43e4-88e7-b1bb2c91005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>taxOfficeSelector</value>
      <webElementGuid>7c6de048-e471-4435-be4d-202d14458600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1cf83ab7-93b4-493c-af0d-ac3534814ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent</value>
      <webElementGuid>78fdd74f-6aa8-41e0-8739-b11f9275181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('TXOFF', this);</value>
      <webElementGuid>85ab541c-b313-47aa-a37a-5532e2cf199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f741956-fa64-407d-9a54-fd7d1f22bec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ADDR_TAX_OFFI_DOM</value>
      <webElementGuid>49df2856-09a3-4128-a9e7-c55d0a4ab263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>f0312036-1717-4e17-9dd2-439f46f20d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RF AMBRIZ</value>
      <webElementGuid>6f9329a2-506d-456b-b2fa-56ec7ac65b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent&quot;)</value>
      <webElementGuid>1b84a301-b7cc-44cc-99d3-3905f2968f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>7b267565-294c-435d-8c19-99dc67002ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent']</value>
      <webElementGuid>304fc7b5-622b-4e3f-ac93-3f6e9a7a669f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[18]/td[2]/select</value>
      <webElementGuid>5d7a89a9-f0d5-45aa-9f90-b08a28743085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repartição Fiscal de Domicílio'])[1]/following::select[1]</value>
      <webElementGuid>7bbaa2bc-d18e-4ec9-9aed-5e9a2a40e829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local de Referência'])[1]/following::select[1]</value>
      <webElementGuid>2d457018-3ec6-4c83-bf73-11aff5e1494c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observações'])[1]/preceding::select[1]</value>
      <webElementGuid>d69428b7-42ff-4ced-add5-cfa60058771d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Georeferência'])[1]/preceding::select[1]</value>
      <webElementGuid>3e4ba9b9-3771-4c1c-865b-f3b956456f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[18]/td[2]/select</value>
      <webElementGuid>76fbc167-f3be-4f7f-ab8b-54ab4d94ccdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'boGroup_select_addressInformation_addressTaxOfficeOfDomicile_asCurrent' and @type = 'text' and (text() = 'RF AMBRIZ' or . = 'RF AMBRIZ')]</value>
      <webElementGuid>5e58b57f-9e09-474e-a8ec-a3d2b6da0cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
