<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-VerificarFormulario</name>
   <tag></tag>
   <elementGuidId>3d005c10-eb4b-4816-8d8d-124607c1c520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Verificar Formulário']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'oraButton oraDefault' and @type = 'button' and @value = 'Verificar Formulário' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.oraButton.oraDefault</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dac19c02-9db8-4fe5-a756-1b0d979a4a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraInvokeSS('C1-AppVRules', null);getDescriptionInfo();windowLoad(); highlightFieldWithErrorsActivityDataList(); highlightFieldWithErrorsPartnersSubsidiariesAndBranchesList();
</value>
      <webElementGuid>14c115e0-a4af-4eca-ba22-fe75a2cce645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oramdlabel</name>
      <type>Main</type>
      <value>CHECK_FORM_BTN_LBL</value>
      <webElementGuid>78e7484e-1681-4782-8d3a-2a12003ec050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton oraDefault</value>
      <webElementGuid>8a7b14ee-3b63-42b6-a928-128a4d22949d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf95503e-1a7c-44a4-8523-7dd9c70d068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a7f35821-26bb-46c7-aea7-702f70aad4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verificar Formulário</value>
      <webElementGuid>d58c446c-9145-49bb-8fd0-3849c788fe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableException&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;oraButton oraDefault&quot;]</value>
      <webElementGuid>36ae4459-3a45-43c6-b5f6-aa466144516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>fe8b7921-936a-4875-94c6-dc45712a36a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Verificar Formulário']</value>
      <webElementGuid>0b97c2f1-bdc3-4399-94f4-f0d6da0866ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableException']/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>3b3bdfd2-f46b-4cd7-9196-cd7a91335a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7c9d216a-d338-4671-a090-0b3f15a631dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>6e93e2b4-0949-4bb5-8bac-cbece5364db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
