<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Gravar</name>
   <tag></tag>
   <elementGuidId>7e9c0e0e-aa54-4795-ad93-ecc046a6ed0a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.oraButton.oraDefault</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'oraButton oraDefault' and @type = 'button' and @value = 'Gravar' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7db2d9b3-8a82-4d3c-bd09-1c8658f470b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton oraDefault</value>
      <webElementGuid>69a861b5-1c36-4652-a11d-5fbab3815198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7764b80-8d75-42c3-842d-010b874a7218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d3bc2fda-43f5-4c98-8c47-03483fd5adff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Gravar</value>
      <webElementGuid>4fb0b7cd-34c2-4ab3-a854-8077e1ef51d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>60f2a30b-d3c0-4939-a56d-bddc8cb49f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Gravar']</value>
      <webElementGuid>2574dca8-ba19-47c6-8ec1-52720a80893a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
