<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Validar</name>
   <tag></tag>
   <elementGuidId>f4b63506-8b74-454c-9d41-713da7cc1c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Gravar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.oraButton.oraDefault</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @value = 'Validar' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b78891a-38cf-46d1-bc52-828264e7ae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton oraDefault</value>
      <webElementGuid>fa76b178-f6df-4a9f-afc7-ca001691b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2f0c28e-89a2-4e0f-9d15-57872a6ae2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0b11ec56-97b2-48c5-a5f1-a1fc4a81613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Validar</value>
      <webElementGuid>12e9f2bb-f183-4b19-bb14-a5bfb4fb63aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frameZoneMap_1</value>
      <webElementGuid>49af9a25-c8ce-4a1a-b1ca-aca1e5bd2aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Gravar']</value>
      <webElementGuid>10d3592c-f72c-42f3-ab88-7e899c0ac9be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
