<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-ComprovativoCadastro</name>
   <tag></tag>
   <elementGuidId>0be2309f-79f0-46f2-9374-33c6a098fca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @value = 'Comprovativo de Cadastro' and @ref_element = 'Object Repository/Page/Principal/frameZoneMap_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.oraButton.oraDefault</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbf8ce80-bf4e-403d-b3a8-b53de6cec68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton oraDefault</value>
      <webElementGuid>8e7a0572-9511-444f-bcc4-bc37dc140ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72ab4047-4128-4499-b285-1d7b44001d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a3b13727-a131-489c-8992-d20a334cc91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Comprovativo de Cadastro</value>
      <webElementGuid>94748055-affd-44f8-918e-5487ac01948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oramdlabel</name>
      <type>Main</type>
      <value>CM_PRINTPROOF</value>
      <webElementGuid>fa9ed72c-19d6-41c1-b8bc-887e8c98c270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frameZoneMap_1</value>
      <webElementGuid>6a14d691-25d4-4b4a-9289-25d7a3e2256c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
