<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Publicar</name>
   <tag></tag>
   <elementGuidId>a47f8470-78fc-4ff7-b226-ca6004447870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.oraButton.oraDefault</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @value = 'Publicar' and @ref_element = 'Object Repository/Page/Principal/frameZoneMap_1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4524187a-ae62-4c0c-8430-bbaea5edd8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton oraDefault</value>
      <webElementGuid>f01e9430-79ea-4e08-ae1b-ece434fb638c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>991e5a83-c0f9-48af-afa5-a109e9e3873c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>985c08f6-e61d-4763-a545-d84ffd8686d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Publicar</value>
      <webElementGuid>b50f32bc-c9ba-43f4-8f61-cc2eaa949c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frameZoneMap_1</value>
      <webElementGuid>30b6bd56-02c1-445c-8eb3-ba54c7f36b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Publicar']</value>
      <webElementGuid>f8ae5fcc-5aa8-43eb-b708-d07d2be1a798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
