<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>autarquia</name>
   <tag></tag>
   <elementGuidId>cd6580c2-7236-497e-9e14-d880e5820c57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iva_autarchy_asCurrent_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iva_autarchy_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'iva_autarchy_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_AUTARCHY' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9395224c-da75-41a0-94b6-dbe350817b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>968d17df-23e4-4d78-b5c4-fad97b9c8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>autarchy/asCurrent</value>
      <webElementGuid>ed233fa8-5ca6-4c0c-ae30-e5b167b4d7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>2a363386-dac3-4ee3-aaf8-69bda3c5dffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7d14e26-7918-4f48-980d-59e7a40b8eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this); handleVatActivityPlace();</value>
      <webElementGuid>0f629427-8c41-4f99-8643-06a350dae924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>9cd9b818-ec34-415c-82a1-7800d3c52ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iva_autarchy_asCurrent_0</value>
      <webElementGuid>30b50fcc-b161-4e3e-a3c8-cccc4129b134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_AUTARCHY</value>
      <webElementGuid>e4563b25-57fc-4861-975f-a62a19a93589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:254</value>
      <webElementGuid>383cc3bf-48da-4345-89d9-9842171bcede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>autarchy/asCurrent</value>
      <webElementGuid>d982072f-7300-4c08-a177-b42fb48c69e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>94d76e59-0e23-4a59-8d76-3188b8b2dd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>3716a991-a576-41da-8f7f-5995cac31715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>6e9bdea8-9739-4196-b21e-8af9b6bd359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>iva_autarchy_asCurrent</value>
      <webElementGuid>570d6a28-39df-4676-b72f-3aeacbed7824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>iva_autarchy_asCurrent</value>
      <webElementGuid>371ab084-23f6-4ca3-b076-fdd7c2ccb921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iva_autarchy_asCurrent_0&quot;)</value>
      <webElementGuid>a7ab8b65-a73d-4d87-9c08-e7694182fa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>51776674-f145-4fb6-ad07-46683da749b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iva_autarchy_asCurrent_0']</value>
      <webElementGuid>55da7fe3-d8e6-4a97-9b2d-d71bb3bbe494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>09c505bf-bdc0-49b2-b91a-1ebc407d93c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>c9bb838c-b34c-4d42-9ebd-c2e629b9b34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'iva_autarchy_asCurrent_0']</value>
      <webElementGuid>02effff3-d45b-4765-8814-55129e1b48c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
