<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>comuna</name>
   <tag></tag>
   <elementGuidId>6c40a1da-78d3-433e-a4e3-b58f519a2390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'iva_commune_select_0' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iva_commune_select_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='iva_commune_select_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>32b2267f-455b-4d29-a859-dfb3cbeaacc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>communeSelector</value>
      <webElementGuid>fd87ac1d-ee7c-4a94-965c-2d38ec256039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ec64c9ef-9b72-4f99-9e28-8338e3595782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iva_commune_select_0</value>
      <webElementGuid>ede6a9f5-7945-4675-a972-8c152c05b880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('COMM', this); handleVatActivityPlace();</value>
      <webElementGuid>16e0cee7-239e-4df7-8456-018deb7e38f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46d73cb5-4ba2-4b10-8b47-a1920dc9fb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_COMMUNE</value>
      <webElementGuid>5b0f4505-e9ca-42b3-b6ca-4828200873c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>095c30cb-7f87-4cb8-a1a8-05e9ec61b0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>iva_commune_select</value>
      <webElementGuid>b9360198-68ae-4995-983c-016ddd20c741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>iva_commune_select</value>
      <webElementGuid>d2aa9db6-ca56-4cea-a488-b9ebd1f79d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
AMBRIZBELA VISTATABI</value>
      <webElementGuid>43d65c3c-2c50-48fa-ade0-9d9042da67c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iva_commune_select_0&quot;)</value>
      <webElementGuid>41a6edf8-c174-4bee-b6a7-cc7f65a2c7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>fd00b8b3-f126-4915-8e15-7c6ada52e12a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='iva_commune_select_0']</value>
      <webElementGuid>a53cbc2d-08cb-491a-b1c8-594c7aa2c8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>60281d70-1d94-4b06-820e-45f837b9c650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[1]/following::select[1]</value>
      <webElementGuid>6aed0798-debe-4251-8839-199ed036a024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[3]/following::select[2]</value>
      <webElementGuid>82a19ec2-967a-4ffe-9501-0bbbd3e87d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nº do Estabelecimento Comercial'])[1]/preceding::select[1]</value>
      <webElementGuid>c80e426e-1ac0-4af4-924c-c2cf2fc0d632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspensão ou Cessação de Actividade'])[1]/preceding::select[1]</value>
      <webElementGuid>b11844b0-b4bc-42af-b28d-8998c1b20ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>b2b22c59-03c0-47f8-b4f4-8a3890c358a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'iva_commune_select_0' and @type = 'text' and (text() = '
AMBRIZBELA VISTATABI' or . = '
AMBRIZBELA VISTATABI')]</value>
      <webElementGuid>85a79e5b-ebcb-469f-95f8-7a547f73a65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
