<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>conferePlenosPoderesDeclarativosAoContabilista</name>
   <tag></tag>
   <elementGuidId>be90b0d9-e52f-4057-a0e9-811fe5bce5db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_ivaInformation_confereContalPower_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_ivaInformation_confereContalPower_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_ivaInformation_confereContalPower_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_VAT_REGFORM_3' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3b52d51-cd83-4718-8b5b-d06a3637cc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c7fa77d0-f4bc-4937-8812-7e7b02e73558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/confereContalPower/asCurrent</value>
      <webElementGuid>78811dee-b1a2-488f-974b-573c24c050d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3d093dcf-35da-4719-b6f8-f5ff80fd211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>46efa2f7-f511-499b-a2a9-b2866aea3e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_ivaInformation_confereContalPower_asCurrent</value>
      <webElementGuid>468c8a7f-5bf6-4812-a9df-df5800cb1ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_VAT_REGFORM_3</value>
      <webElementGuid>d1745ac0-7351-438b-a943-1d9544c9c3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:60</value>
      <webElementGuid>c054183b-c9e1-4f0f-96df-2e3d08c130e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/confereContalPower/asCurrent</value>
      <webElementGuid>c203b4cd-c347-476b-bfb2-58b5b438d964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>09c4083c-fbdb-40b0-9567-50fb86362189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_ivaInformation_confereContalPower_asCurrent&quot;)</value>
      <webElementGuid>d1352c62-055a-4cbf-86bc-72ac87269413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>65070fb0-dbfb-4bb3-abdd-63883d3a6d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_ivaInformation_confereContalPower_asCurrent']</value>
      <webElementGuid>289e48ef-10a8-45f3-9cde-62ad27171296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[25]/td[2]/input</value>
      <webElementGuid>85d0f9eb-3781-419c-85bc-7440a2f1b0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td[2]/input</value>
      <webElementGuid>5d875a7d-618e-404f-9e90-1c9dd1b05d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_ivaInformation_confereContalPower_asCurrent']</value>
      <webElementGuid>ff5ea1b6-b89f-4efc-be25-71b2dab2ead3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
