<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>localizacaoDaContabilidade</name>
   <tag></tag>
   <elementGuidId>32ca059d-b686-4838-a042-12971ac805e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_ivaInformation_accountingLocalization_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_ivaInformation_accountingLocalization_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_ivaInformation_accountingLocalization_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_VAT_REGFORM_02' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f184eec-7e4a-49d1-8f5c-92983d6be357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8b60e84a-ccd1-4d48-8436-ecee785a18ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>b8b897a4-dc5f-4879-bfb1-a9c1bb974050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/accountingLocalization/asCurrent</value>
      <webElementGuid>9fd91f70-97a6-498a-bdf8-c8d04f328afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>dda7fc39-916c-4bbc-8099-89ae01ba342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14891444-f788-499a-95af-717064d2f090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_ivaInformation_accountingLocalization_asCurrent</value>
      <webElementGuid>7b1ce166-cea2-4f14-ad61-b1e9b1fc8485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_VAT_REGFORM_02</value>
      <webElementGuid>8c8b9035-ee77-4f0d-a554-e821e59026d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:200</value>
      <webElementGuid>16f31c2f-e08c-45b9-8c7a-df4455cbd67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/accountingLocalization/asCurrent</value>
      <webElementGuid>08ea2557-1b33-4354-a58b-b0da1160f7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>46b5da4c-dba8-4eff-b240-5d3c63163eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>45228614-909c-4020-b343-ecd9aa363910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>7b703996-0013-4458-93a2-6b2b06894192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_ivaInformation_accountingLocalization_asCurrent&quot;)</value>
      <webElementGuid>e9c9400c-18c4-411a-859d-bb103bbcce33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>4b7e7114-d67a-4e50-b899-10e7de000e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_ivaInformation_accountingLocalization_asCurrent']</value>
      <webElementGuid>8860fb2f-1673-4d40-966e-26072dbba57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[24]/td[2]/input</value>
      <webElementGuid>0ce48fe4-a990-4423-9178-3df6927ccf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[2]/input</value>
      <webElementGuid>e275a0fe-485b-40b0-8f1e-6da64d56f06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_ivaInformation_accountingLocalization_asCurrent']</value>
      <webElementGuid>4ce5fc03-db57-4528-824a-233d3e79c42d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
