<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>municipio</name>
   <tag></tag>
   <elementGuidId>74a68dc5-ab92-4698-9352-06c7325ab47f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='iva_municipality_select_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iva_municipality_select_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'iva_municipality_select_0' and @aria-labelledby = 'C1_AS_CURRENT CM_ADP_MUNI_PRIN_ACT' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c484ae51-990c-43a4-bc41-4468b2391720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>municipalitySelector</value>
      <webElementGuid>57ddc8e9-7872-4781-a2da-984ac4c3240e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bb7a49bb-3a4e-4109-9934-98b96c2fd9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22116702-82b7-4a5a-b087-ed09063d37b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iva_municipality_select_0</value>
      <webElementGuid>80b19468-bc69-45d8-977d-540c394ee3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ADP_MUNI_PRIN_ACT</value>
      <webElementGuid>c7787bde-a455-40c7-a8a7-33a00d6ca94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('MUNI',this); handleVatActivityPlace();</value>
      <webElementGuid>7404595f-6041-487a-a05d-6f1d11d1c42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>d98666e3-3f84-4ad0-82ec-317aba40e067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>iva_municipality_select</value>
      <webElementGuid>36a8122e-dd3b-45a2-ad9b-8220e81f3a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>iva_municipality_select</value>
      <webElementGuid>ab678995-7930-4e21-9b4f-cefad4039142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM</value>
      <webElementGuid>d2737e45-a193-4cf8-bd8e-007e20fd5850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iva_municipality_select_0&quot;)</value>
      <webElementGuid>91b43c06-586b-4b9a-b700-c0905615e2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>4bebbb2c-71ab-4b94-b555-15cc31479d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='iva_municipality_select_0']</value>
      <webElementGuid>1c0c9b78-abd7-485c-a52e-5ba7dcac53c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>64dd7e34-7f91-464a-b366-2539f36933ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[3]/following::select[1]</value>
      <webElementGuid>02799935-d5e6-489c-a51a-f038848886c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[1]/following::select[1]</value>
      <webElementGuid>7a8e5244-529f-4eb9-9344-dbd1c010ade4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[1]/preceding::select[1]</value>
      <webElementGuid>82af173d-cef3-4853-8c7b-95897f40ac42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nº do Estabelecimento Comercial'])[1]/preceding::select[2]</value>
      <webElementGuid>01bed8bd-a215-4090-86b5-d6d95f4848bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>04cec758-9277-4cd9-ab50-09e20ff45a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'iva_municipality_select_0' and (text() = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM' or . = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM')]</value>
      <webElementGuid>247c6c1e-168f-4be9-8456-4f1b6cb7481e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
