<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nEstabelecimentoComercial</name>
   <tag></tag>
   <elementGuidId>e9f8bd2c-7282-4cc9-a538-4515dc42093f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iva_establishmentNumber_asCurrent_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iva_establishmentNumber_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'iva_establishmentNumber_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_ESTABLISHMENT_NUMBER' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26db0b27-219d-4aac-b1fb-dc2fbb1038c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9ea2fc03-c264-483d-ace6-fc0fc7054838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>establishmentNumber/asCurrent</value>
      <webElementGuid>2626922a-6b1f-4cf4-a060-08de8f2a20a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>601e6171-805c-4d5d-878f-5e4a43d01358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c60ceaa7-0f0b-49b8-b6c1-d531e2af0c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this); handleVatActivityPlace();</value>
      <webElementGuid>bd73bfdc-bbb4-4609-a414-04aa70365179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iva_establishmentNumber_asCurrent_0</value>
      <webElementGuid>00f1cd1b-17f2-4212-9991-e836f060b4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ESTABLISHMENT_NUMBER</value>
      <webElementGuid>3e2f3915-8027-4351-b4d4-252f2f978c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:10</value>
      <webElementGuid>3040e292-71c6-4e75-ba6f-22de032a53da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>establishmentNumber/asCurrent</value>
      <webElementGuid>dccbf62c-4e17-44ef-bca5-ecf14b1917d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>04b19a07-4d87-4cac-a038-eb794925a952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>99a15ed0-824e-4db4-a181-e0cc8db809c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b5ed86f4-3451-4c87-a696-c40b9d5299c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>iva_establishmentNumber_asCurrent</value>
      <webElementGuid>d8382e1f-9d18-4805-8848-6f004362f0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>iva_establishmentNumber_asCurrent</value>
      <webElementGuid>babfe45b-c834-41f0-a121-65b6c8441bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iva_establishmentNumber_asCurrent_0&quot;)</value>
      <webElementGuid>6fa9acab-8318-4f58-b961-b4c1ecdbc42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>eb7642fb-e7b9-4ed5-9a57-3ff523336c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iva_establishmentNumber_asCurrent_0']</value>
      <webElementGuid>34d85f8d-29ec-4d43-8af0-7d9ef4d3150a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>ce46a337-d9d3-4259-9f59-2297ddf68f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>0d156600-9eef-401d-a66d-da170ae3fbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'iva_establishmentNumber_asCurrent_0']</value>
      <webElementGuid>49641ac4-8c2f-404d-8c75-0283252e3460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
