<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>obrigadoCativarIVA</name>
   <tag></tag>
   <elementGuidId>de6b58b4-15c8-4c17-aafd-3cd6bbd257c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_MODELO6_TAXDEDU_THANKST_0' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6385001-689e-43cb-b56a-0fcfd5c906fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0ecf6688-0a70-4c2b-bf23-2ee6c64c423d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/thanksToCaptivateVAT/asCurrent</value>
      <webElementGuid>e0291aae-4e20-4fc7-8a4e-d4c6764ba8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>49137958-ae89-473d-b52f-c0955c2d909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>d7817384-c48e-4edc-853d-205369e16d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent</value>
      <webElementGuid>6b08f414-5b71-43e0-bb8e-f723addc407c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_MODELO6_TAXDEDU_THANKST_0</value>
      <webElementGuid>481f3d9e-59ad-4923-9f3c-e9453de1271b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>a316b37f-711c-4d8c-93f9-64b2f70b94c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/ivaInformation/thanksToCaptivateVAT/asCurrent</value>
      <webElementGuid>0b6bffd9-f00d-4639-9fe1-13a0d85eb103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>47feae6c-e902-45c8-a58e-d73d3bb8b84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b5a216f-dd98-4a3e-b974-4fc82d3852f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent&quot;)</value>
      <webElementGuid>04c82f24-da92-4d8c-b2ac-9402e75debf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>e3fc366e-4db6-4104-845d-7cc056092279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent']</value>
      <webElementGuid>2c2b4293-07c6-44bf-a00c-9e7039b4c7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>2f752d48-cc9b-449f-9ef5-69a56f8b982d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>94b766ec-86b7-4c84-8698-02d7921dbc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_ivaInformation_thanksToCaptivateVAT_asCurrent']</value>
      <webElementGuid>80fff6d3-6d27-41a3-938e-32f6bd4f7df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
