<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>provincia</name>
   <tag></tag>
   <elementGuidId>93022571-bfb6-42a1-b202-46fc35dc59b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='iva_province_select_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iva_province_select_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'iva_province_select_0' and @aria-labelledby = 'C1_AS_CURRENT CM_ADP_PROV_PRIN_ACT' and (text() = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE' or . = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE') and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de IVA/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4dac64f6-a7d2-4dc3-9ea0-b83f7ad24028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity provinceSelector</value>
      <webElementGuid>7bc1cecb-e97e-43bb-bf27-9a2fdfe37aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>70c6e41d-6f37-4c93-92cf-349c580780af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2aedb419-00fc-4c87-9dbc-52e6a056aa8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iva_province_select_0</value>
      <webElementGuid>64b18bcc-e781-4fb5-b460-938bd88678a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('PROV', this);setPkChild(this); handleVatActivityPlace();</value>
      <webElementGuid>d8f848c0-55a6-4b4d-8dd0-33ebd5a95004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ADP_PROV_PRIN_ACT</value>
      <webElementGuid>9133bae1-310e-43a9-ad75-386edafc42fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>5fd04058-cdfa-4aa0-b875-fddd0e623975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>iva_province_select</value>
      <webElementGuid>4fd86f1f-a407-46f8-91ec-195e6efa9162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>iva_province_select</value>
      <webElementGuid>8de4e779-74e8-4a4b-a0d0-a64e52c59cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE</value>
      <webElementGuid>8633eba8-99e2-41aa-b506-1210cb05030b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iva_province_select_0&quot;)</value>
      <webElementGuid>9fd3cb34-68b8-4bdd-b96d-9dd081966a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>3ff82c42-0c02-486d-93b6-74ab767251bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='iva_province_select_0']</value>
      <webElementGuid>b427c6d7-ee8c-4cc0-a2f3-6d33aae207da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ivaInformationsSectionHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>fd9f687a-4fb6-4358-9371-9a4a34eb8703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Província'])[3]/following::select[1]</value>
      <webElementGuid>7ea48b2b-7654-4f99-9e91-71f4cf975048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locais Aonde Exerce Actividade'])[2]/following::select[1]</value>
      <webElementGuid>147c0bb6-0bef-4f18-8da8-990cea4a333d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[1]/preceding::select[1]</value>
      <webElementGuid>b283f5b1-fa38-4298-9cfe-430281e3aeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[3]/preceding::select[1]</value>
      <webElementGuid>13f41aae-9a67-44bd-9777-11e274925a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>a50983f6-0324-420f-9883-1ad499cdadf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'iva_province_select_0' and (text() = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE' or . = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE')]</value>
      <webElementGuid>c242e404-a045-4673-94c7-4209f1884926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
