<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cancelar</name>
   <tag></tag>
   <elementGuidId>517d7a0c-e501-48cb-bf79-36720370d8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input.oraButton:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input.oraButton:nth-child(4)</value>
      <webElementGuid>961802e6-24ca-47f0-aa60-f00244f3a52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>10243360-9eb5-4286-a29d-26048455b469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>d0b2cef6-5f24-4162-9f64-88f40097d700</webElementGuid>
   </webElementProperties>
</WebElementEntity>
