<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assalariadoPrestadorServico</name>
   <tag></tag>
   <elementGuidId>50ccb86d-e299-46af-a2ad-cf7b2b2ef3de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_salariedServiceProvider_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_STDREG_DTLNAO_EMPORS_0_SW' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes Para Nao Residentes/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_nonResidentDetails_salariedServiceProvider_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_nonResidentDetails_salariedServiceProvider_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59e77634-dd6d-43dd-a884-9aca2cba7f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nonResidentCheckbox oraDefault</value>
      <webElementGuid>cc26a371-dd08-4c1d-95df-ec54ff05a875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fab9dde9-583d-44e3-a4c4-f6cea3ac2c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/salariedServiceProvider/asCurrent</value>
      <webElementGuid>8461d680-7610-40b3-8e52-179656c4dbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>20587309-1e1e-482b-a7d0-a8b8b5fa47fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>efbb724a-be97-4af6-a91d-2d9b81c337ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_nonResidentDetails_salariedServiceProvider_asCurrent</value>
      <webElementGuid>84b17f8d-f0e0-4d36-af50-633029533996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_STDREG_DTLNAO_EMPORS_0_SW</value>
      <webElementGuid>7edcf5d6-e559-4f52-adca-28d2245190ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>cbc45147-3924-40d2-9ddd-b41949490adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/salariedServiceProvider/asCurrent</value>
      <webElementGuid>86942154-5a0c-4415-9e94-d71be2a5360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7abc0ec6-680a-40e9-87da-a444a24bfa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_nonResidentDetails_salariedServiceProvider_asCurrent&quot;)</value>
      <webElementGuid>4e5153a2-9125-4f32-9b0b-bb59f0f30577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>061a0bf9-1786-4d6b-90ab-19d35ca9a528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_nonResidentDetails_salariedServiceProvider_asCurrent']</value>
      <webElementGuid>33993f1e-555c-45f9-8e61-66ef8f9d9580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='assalariado_sw']/td[2]/input</value>
      <webElementGuid>d4d6b660-d4e7-49a3-9758-72ca54faec30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>4dae8269-ae0a-49bf-a697-f54aa6221c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_salariedServiceProvider_asCurrent']</value>
      <webElementGuid>476a192b-c458-431e-af49-5e7b2ece07ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
