<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>diplomataRepresentacaoConsular</name>
   <tag></tag>
   <elementGuidId>91012af4-a9ba-4c98-b805-6db095c5fab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_diplomatConsularRep_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_DIPLOMAT_SW' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes Para Nao Residentes/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_nonResidentDetails_diplomatConsularRep_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_nonResidentDetails_diplomatConsularRep_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5051abd-1433-4b3d-9b11-928265065b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nonResidentCheckbox oraDefault</value>
      <webElementGuid>75892987-a759-4065-94bb-2fc1561ca4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>23c893c2-aa61-4e79-ae96-cf5cb3e7727c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/diplomatConsularRep/asCurrent</value>
      <webElementGuid>0193bb74-6769-44a0-8b6e-31fc104cfccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b89534a1-8b17-47ae-817f-027bcf35e147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>8c5a8ae2-2a6e-46bd-be1e-99a6cc840161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_nonResidentDetails_diplomatConsularRep_asCurrent</value>
      <webElementGuid>587bacb4-2f5e-4c20-869e-9a7a12ae8ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_DIPLOMAT_SW</value>
      <webElementGuid>ac891f8a-0413-4477-829f-9d71686a1fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>8ebb60e5-ef62-4d44-8165-4d6779bf0a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/diplomatConsularRep/asCurrent</value>
      <webElementGuid>1d208b25-5811-4fb1-99c2-c9dae17f70b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>614dcf12-73f6-4bcb-94f5-54d4b23d1ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_nonResidentDetails_diplomatConsularRep_asCurrent&quot;)</value>
      <webElementGuid>d281c537-220d-40b4-815c-b0c8f8e6eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>03002ac6-d073-456e-a4d1-a89d7d8fa353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_nonResidentDetails_diplomatConsularRep_asCurrent']</value>
      <webElementGuid>466cb2e7-f490-45b0-b230-4daa40af0c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='diplomat_sw']/td[2]/input</value>
      <webElementGuid>ce5e92b9-80ef-4f6d-ac5c-e11c156320b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/input</value>
      <webElementGuid>b4231060-a843-4a38-9efa-bb931ea03930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_diplomatConsularRep_asCurrent']</value>
      <webElementGuid>ce7aa8c9-8601-4464-9d43-e9d88ec68f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
