<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>investidorDirecto</name>
   <tag></tag>
   <elementGuidId>dd506a7b-8f05-40cf-bd45-a3a10ab5cf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_directInvestor_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_DIRECT_INVESTOR_SW' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes Para Nao Residentes/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_nonResidentDetails_directInvestor_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_nonResidentDetails_directInvestor_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f779062f-c574-4664-a953-3a82f880063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nonResidentCheckbox oraDefault</value>
      <webElementGuid>a4aeeae5-484d-4e06-86d1-f3b02b229020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9944b86a-8f3c-4f37-91d1-a5abf870344e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/directInvestor/asCurrent</value>
      <webElementGuid>12c1e8f5-18bf-44d4-b4c1-f658622ef292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>38112617-d43f-4ed6-a482-2e66f0bfa274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>a67e5aee-e518-4e9d-89a9-aad3aca77cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_nonResidentDetails_directInvestor_asCurrent</value>
      <webElementGuid>de56511c-a2e1-4628-8692-20f6c369e61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_DIRECT_INVESTOR_SW</value>
      <webElementGuid>5f7d28e2-a2fd-40a9-9ddc-a0efa0daa225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>0f1dd673-46e1-4cb0-80d7-65c8244fbc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/directInvestor/asCurrent</value>
      <webElementGuid>9f51d1ba-f629-48a4-8ea9-d74325b9d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c21bb97-9e3a-4568-a059-5a43ff031dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_nonResidentDetails_directInvestor_asCurrent&quot;)</value>
      <webElementGuid>d64b50ae-04be-4dc5-bacb-87faf0b25d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>bbbf78b3-fa07-441d-a026-2699c9d96013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_nonResidentDetails_directInvestor_asCurrent']</value>
      <webElementGuid>24382a9a-2075-4d69-9e66-8e14020de37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dir_investor_sw']/td[2]/input</value>
      <webElementGuid>60d4fc6d-1297-4825-bb9a-433f25d4947c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>a482165d-b6c3-4ef4-bb9c-127cae1639f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_directInvestor_asCurrent']</value>
      <webElementGuid>99764a49-e49d-4286-860b-93fb04a5d18f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
