<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Form</name>
   <tag></tag>
   <elementGuidId>1604e70a-dcdc-4e42-8e59-ef4efe769f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@oramdlabel = 'CM_STUDREG_NONRESIDEN_0' and @class = 'clickable' and (text() = 'Detalhes para Não Residentes' or . = 'Detalhes para Não Residentes') and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes Para Nao Residentes/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='nonResidentDetailsNavRow']/td/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nonResidentDetailsNavRow > td.cmFormNavigationCell > a.pseudoLink.oraNormal > span.clickable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4b014c7-317f-4d09-be2b-3fae290664c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oramdlabel</name>
      <type>Main</type>
      <value>CM_STUDREG_NONRESIDEN_0</value>
      <webElementGuid>c7fa25e6-f29c-4ca7-8e02-dd06fb9323a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable</value>
      <webElementGuid>527550b0-aeee-4ea6-8c22-acb9d3e8e26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detalhes para Não Residentes</value>
      <webElementGuid>26076e59-db60-4cba-93b3-a59999fe4f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nonResidentDetailsNavRow&quot;)/td[@class=&quot;cmFormNavigationCell&quot;]/a[@class=&quot;pseudoLink oraNormal&quot;]/span[@class=&quot;clickable&quot;]</value>
      <webElementGuid>f65a9466-3e07-45d1-bcea-badba55f2f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>6b0632fb-c040-4185-b21f-3bd224e141d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='nonResidentDetailsNavRow']/td/a/span</value>
      <webElementGuid>7bba72b7-0ab5-48c9-a1c0-e0071c54ccc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enquadramento em Impostos'])[1]/following::span[1]</value>
      <webElementGuid>f85300d8-ff61-41c9-a3a6-f287a5f81279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalhes de Registo'])[1]/following::span[2]</value>
      <webElementGuid>0fce5881-4be9-4a49-8270-684a1f311755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Representação Fiscal'])[1]/preceding::span[1]</value>
      <webElementGuid>66a8afc2-4afd-42f2-b7fc-e1ed12382293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalhes de Identificação de Contribuinte Singular'])[1]/preceding::span[2]</value>
      <webElementGuid>41fff34f-1f98-449b-ae05-83bd7f97a039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detalhes para Não Residentes']/parent::*</value>
      <webElementGuid>810eb117-f5bf-4a53-883c-5a225834420e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/a/span</value>
      <webElementGuid>34d86fb6-6c84-4537-ba46-9e5a34664dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Detalhes para Não Residentes' or . = 'Detalhes para Não Residentes')]</value>
      <webElementGuid>b0a98972-4eeb-4c00-a13c-08b644ad6ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
