<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patrimonioAutonomo</name>
   <tag></tag>
   <elementGuidId>ed79293a-e02d-41b2-84f3-301e541ce5c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_heritageAutonomous_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_nonResidentDetails_heritageAutonomous_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_nonResidentDetails_heritageAutonomous_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c1ffe81-c283-4bc2-b230-87a055a4e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nonResidentCheckbox oraDefault</value>
      <webElementGuid>0dcbfb1b-9f9b-4c34-95c6-40be4e0b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f71c54d1-6c95-47a4-b95a-1aef1a3aa9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/heritageAutonomous/asCurrent</value>
      <webElementGuid>ccae160f-e5e6-4966-a18b-02b6bc1cebe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>31d76ee2-3f7f-4957-a6bf-694a45d5b007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>9bb91f87-80d3-4f44-a083-39f7d445f975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_nonResidentDetails_heritageAutonomous_asCurrent</value>
      <webElementGuid>ae3d639a-87e7-447b-9e03-25e5503cb462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_HERITAGE_SW</value>
      <webElementGuid>336813d3-6bf6-4e27-a855-476d5ce90417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>boolean</value>
      <webElementGuid>c4ecfc09-e191-4ea3-a099-605c9e8027aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/heritageAutonomous/asCurrent</value>
      <webElementGuid>c18f19ef-46bd-4316-ab06-5cb050af64fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50f84e0a-9343-4039-9b7f-050d8296e636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_nonResidentDetails_heritageAutonomous_asCurrent&quot;)</value>
      <webElementGuid>b61c867f-aa3d-4920-b51d-d64201e8055d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>6ed2653e-bb92-458d-9510-3512d116ca98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_nonResidentDetails_heritageAutonomous_asCurrent']</value>
      <webElementGuid>1c21938c-4757-4ed1-b24c-80f0999f4a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='heritage_sw']/td[2]/input</value>
      <webElementGuid>17daa75c-18e8-414b-8bb0-7db397a56e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>be5f76e9-f029-46c6-b009-cf837bc81fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_heritageAutonomous_asCurrent']</value>
      <webElementGuid>02bb2f6b-f13d-4581-a422-0c03d9ea038c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
