<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>representadoParaEfeitoDeIVA</name>
   <tag></tag>
   <elementGuidId>a55f8789-01b1-472a-848b-fb0f283bc066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_nonResidentDetails_vatRepName_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_VAT_REP_NAME' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes Para Nao Residentes/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_nonResidentDetails_vatRepName_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_nonResidentDetails_vatRepName_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21c2f876-1eee-4fa9-aeeb-4a42037d06ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vatRepFields oraDefault</value>
      <webElementGuid>c10242a5-0959-4e3e-b723-ac2a286e3ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5561143d-c37b-4f59-8559-2643b77dd8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/vatRepName/asCurrent</value>
      <webElementGuid>9a3e027e-9a72-49cb-a372-bd2f77169dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>104cf420-f050-4058-930a-f1d26201e104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>markAllRequiredIfAnyNotEmpty('vatRepFields');</value>
      <webElementGuid>f12750fb-47d9-417e-9c6f-cff6cdb95e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);markAllRequiredIfAnyNotEmpty('vatRepFields');</value>
      <webElementGuid>2d58dec9-9f64-45a1-9c06-211bbac3f05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d936372-d5b9-41a8-b697-6bb6b6173689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_nonResidentDetails_vatRepName_asCurrent</value>
      <webElementGuid>cc10f4e3-903a-400c-9351-df580c70b748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_VAT_REP_NAME</value>
      <webElementGuid>6e0b050e-6666-4b1c-90ce-0f00b8fae50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:100</value>
      <webElementGuid>bff0c7a7-25a3-4ef5-8bb9-d10cabcea322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/nonResidentDetails/vatRepName/asCurrent</value>
      <webElementGuid>2d8ca0ea-ed4d-438c-a203-270f93b22d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_nonResidentDetails_vatRepName_asCurrent&quot;)</value>
      <webElementGuid>b72f97ec-01a2-4d67-88e5-0140618af60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>3567bd8a-b80a-451c-8e0a-87ca0d1f75c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_nonResidentDetails_vatRepName_asCurrent']</value>
      <webElementGuid>34989474-d2db-4918-816d-761bce14ed32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nonResidentDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>aba20673-fd40-4963-9c84-f7e2f2ff107e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>f2ebc38d-abe0-4182-b4c6-4326f05c4b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_nonResidentDetails_vatRepName_asCurrent']</value>
      <webElementGuid>8af0bf54-d143-4a41-804b-4cc075fb24c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
