<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>municipio</name>
   <tag></tag>
   <elementGuidId>bbbf0f1f-3776-4269-b903-094ba89fe05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_select_originOfTaxes_municipality_asCurrent' and @ref_element = 'Object Repository/Page_Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_select_originOfTaxes_municipality_asCurrent</value>
      <webElementGuid>42f24a6f-0634-48dd-bbda-f7f083d6e45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>municipalitySelector</value>
      <webElementGuid>5fe497e5-fc96-4b1b-bdcf-0c984503b050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>2ae9357d-f8d0-4fbf-8f0d-d441450ee8eb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
