<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dataNascimento</name>
   <tag></tag>
   <elementGuidId>8f8c70b3-b1fc-4f99-8b3d-8f26d6a0ef17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_DATE_OF_BIRTH' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes de Contribuinte Singular/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e5b3044-7a37-4adb-ae3c-0b921d0bf066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6ac72777-0c01-4892-99f5-0c81db941db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/dateOfBirth/asCurrent</value>
      <webElementGuid>21fd4fb1-9711-4c97-a5d1-112ea7e531c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>9f33af1e-8c25-4cd4-bad2-92f8888f613d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>2ef9aceb-7275-4bd7-ae10-de647806c428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1625b3f8-a629-47ea-b241-9efb67829320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent</value>
      <webElementGuid>c7110002-6a5d-45cb-aa81-82f7ac07fc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_DATE_OF_BIRTH</value>
      <webElementGuid>2dee63da-6b39-4718-95c3-6d7eca223cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>445d5ef2-2878-4886-b120-0313e22b854d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/dateOfBirth/asCurrent</value>
      <webElementGuid>fe179e25-c57f-4a0c-9538-d756b3938289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDate</value>
      <webElementGuid>29f85e3f-5cb1-4ad6-a66d-96ea92aa9ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oradatepickerexist</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82fc4761-193e-43cc-9fea-72399296715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent&quot;)</value>
      <webElementGuid>c169bb70-3dcf-4410-b95e-c6834f942980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>7f20c163-8149-4bcc-a2fb-c5d65f414cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent']</value>
      <webElementGuid>41032699-b153-4143-a850-54ceb386c207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singularTaxpayerDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>48152fc5-654f-465b-81a7-5641c2bd0737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>48d90a3a-97d4-4fb9-97f7-41589b9165e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_singularTaxpayerDetails_dateOfBirth_asCurrent']</value>
      <webElementGuid>21067f69-0672-42f2-b8d8-e71292e64b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
