<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Form</name>
   <tag></tag>
   <elementGuidId>4f469198-ade6-474a-9133-c689d3df37d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@oramdlabel = 'CM_SING_TAXP_DETAILS_LBL' and @class = 'clickable' and (text() = 'Detalhes de Contribuinte Singular' or . = 'Detalhes de Contribuinte Singular') and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes de Contribuinte Singular/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#singularTaxpayerDetailsNavRow > td.cmFormNavigationCell > a.pseudoLink.oraNormal > span.clickable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='singularTaxpayerDetailsNavRow']/td/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7d3883f-17f4-4a73-a08b-f9ee84b61722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oramdlabel</name>
      <type>Main</type>
      <value>CM_SING_TAXP_DETAILS_LBL</value>
      <webElementGuid>e32ec4dc-4be8-43de-8b27-01bedc54dc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable</value>
      <webElementGuid>d139857e-5dfd-4bab-855e-329bccb46982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detalhes de Contribuinte Singular</value>
      <webElementGuid>56e09bf3-ecfe-4cbb-a512-d6e005edc89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;singularTaxpayerDetailsNavRow&quot;)/td[@class=&quot;cmFormNavigationCell&quot;]/a[@class=&quot;pseudoLink oraNormal&quot;]/span[@class=&quot;clickable&quot;]</value>
      <webElementGuid>23539e5a-5d68-4484-93c2-2398ef62574f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>214ced40-5fe9-4101-a77e-0f7986dc3677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='singularTaxpayerDetailsNavRow']/td/a/span</value>
      <webElementGuid>d3bcc2da-e77b-4a59-a09e-8d86a00db5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalhes de Identificação de Contribuinte Singular'])[1]/following::span[1]</value>
      <webElementGuid>64bdc893-e3ee-4eba-9113-323b4b0b0d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Representação Fiscal'])[1]/following::span[2]</value>
      <webElementGuid>964dc016-6379-428f-95aa-05b4af744021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outros Detalhes do Contribuinte Singular'])[1]/preceding::span[1]</value>
      <webElementGuid>3606bde7-0edc-4b49-8e01-ec1ad1e94dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalhes do Contribuinte Institucional'])[1]/preceding::span[2]</value>
      <webElementGuid>73a9e528-87a2-48b8-ae5c-bbe358dd1799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detalhes de Contribuinte Singular']/parent::*</value>
      <webElementGuid>8299ccd8-179f-4782-902f-7a9fa57a75b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a/span</value>
      <webElementGuid>baa3bc33-e92a-494b-89c0-6abd1027b563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Detalhes de Contribuinte Singular' or . = 'Detalhes de Contribuinte Singular')]</value>
      <webElementGuid>446e53a1-79d7-4863-84e2-dfb2447912a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
