<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nifDoPaisDeNacionalidade</name>
   <tag></tag>
   <elementGuidId>8142dc7c-18cf-42a8-9fb5-c5d67052bda4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_ORIGEM_COUNTRY_NIF' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes de Contribuinte Singular/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3df7d4fe-edcf-4a02-a274-cd98a621e35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d414024d-856f-47b3-93ea-f7011959511c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/origemCountryNif/asCurrent</value>
      <webElementGuid>cf6a597f-d45a-4cdc-bedc-c36cbdeeed50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>db28245c-ffa0-464a-908b-3968488948c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>bc70d180-ec90-4c5b-ba3c-fd35236e18be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec0305d9-c795-4f51-8861-70ca9bcb0b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent</value>
      <webElementGuid>2300de2a-fdda-4f90-84e4-402ab509e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_ORIGEM_COUNTRY_NIF</value>
      <webElementGuid>543ddedf-9205-464a-832d-334d03fd4c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:20</value>
      <webElementGuid>712448de-b725-41b4-a80f-bf54bc938146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/origemCountryNif/asCurrent</value>
      <webElementGuid>a0629aba-f85e-40b5-868f-a9567dbfb8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>1ac6bbae-e721-42f8-84be-084932229e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>82093bbd-2ca4-486a-b416-f704417c2c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>abad330b-8552-4950-b97c-257295eac1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent&quot;)</value>
      <webElementGuid>afbddb6a-cc87-46da-a976-e610209dfd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>21700f44-4464-4253-8786-fe4be625ac90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent']</value>
      <webElementGuid>a2f5f47f-0821-4ec5-a9d5-6900116ee3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singularTaxpayerDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>f566e494-3cc2-4ac4-866c-2b1a237bd6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>599525f8-1681-45d7-ab3d-842bfc0d0d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_singularTaxpayerDetails_origemCountryNif_asCurrent']</value>
      <webElementGuid>29d20cc0-d836-4b2a-8201-cd8f2ed7ea59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
