<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nomeDaMae</name>
   <tag></tag>
   <elementGuidId>7c58f9e2-be98-43e9-8802-4217ed6ec0db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_singularTaxpayerDetails_mothersName_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_MOTHERS_NAME' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes de Contribuinte Singular/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_singularTaxpayerDetails_mothersName_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_singularTaxpayerDetails_mothersName_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>228bf0c4-882a-42ef-b730-82c82916593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>db99d28d-a7cc-486e-a358-9b86280ef949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/mothersName/asCurrent</value>
      <webElementGuid>4f6b71db-5876-45fd-ae75-3b22f3d5b38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>be9d70c7-39c9-4fcd-8d73-6da7d91230cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>3ca57684-195c-4f16-afeb-52cedc02fd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3ce951f-e863-49c9-99db-d6f77d2cc1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_singularTaxpayerDetails_mothersName_asCurrent</value>
      <webElementGuid>9b2111b6-747e-4c03-bfd1-f0e54625051f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_MOTHERS_NAME</value>
      <webElementGuid>839df5a1-7508-4c07-a251-a376b40ff48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:64</value>
      <webElementGuid>281bb9f7-343a-474c-988c-f4f013d80c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/mothersName/asCurrent</value>
      <webElementGuid>6842c771-c03f-4ce4-8e1f-0544ac461fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>036a2ee9-0828-4f21-b609-e0856665eeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>3f157b2b-5682-4d34-ae42-0911a4859a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>4bf88115-e4c7-4d19-8d6a-3731cec3d532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_singularTaxpayerDetails_mothersName_asCurrent&quot;)</value>
      <webElementGuid>a52fa75d-adb7-463c-b7e2-db7e692bd5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>10541213-0204-4fe6-ba54-cf0932c2b716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_singularTaxpayerDetails_mothersName_asCurrent']</value>
      <webElementGuid>95765ccf-c9f6-4f33-a259-ae6cbfcf9d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singularTaxpayerDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>7fc5809c-adc3-4067-b7f5-579fae01ef91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>6f733d25-bcfd-4765-881e-c2dee451f0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_singularTaxpayerDetails_mothersName_asCurrent']</value>
      <webElementGuid>447ee671-4f5b-440d-9521-3cb0e5235884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
