<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ultimoNome</name>
   <tag></tag>
   <elementGuidId>f8a44fc5-498e-4fb1-9485-a9f0f1703579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_singularTaxpayerDetails_lastName_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_LAST_NAME' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Detalhes de Contribuinte Singular/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_singularTaxpayerDetails_lastName_asCurrent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_singularTaxpayerDetails_lastName_asCurrent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3581f929-26bd-4465-868f-5bb27d48551e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e7062536-458b-4d3f-9526-731dfb2ba535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/lastName/asCurrent</value>
      <webElementGuid>b04262b8-b041-4690-bee8-93ad0c6ef5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>c4ed1762-73ec-4077-9408-c7aeb08d186d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>1551b6f9-4c50-4f85-8b9a-d1760f8f1e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bad65102-7498-4ab5-8468-d2e8a47dc9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_singularTaxpayerDetails_lastName_asCurrent</value>
      <webElementGuid>474bfef7-d7f8-4cad-be93-0fb30ee642d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_LAST_NAME</value>
      <webElementGuid>af7ebecc-0933-49cc-a328-e4e04a63c403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:64</value>
      <webElementGuid>203025f6-a474-42da-a378-9f6f5c90210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/singularTaxpayerDetails/lastName/asCurrent</value>
      <webElementGuid>f6c4f435-2071-40ee-a20c-f8646c964b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>cec1f8ea-003b-4c5c-8c76-9f8f4c000bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>0f6935aa-f090-40cb-91b7-c49912dd1877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>f5bc9867-ccb0-4b5c-b599-662259d3b89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_singularTaxpayerDetails_lastName_asCurrent&quot;)</value>
      <webElementGuid>1ec29073-f099-4369-a8c2-9e3c40197a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>9a6fabbd-7740-49eb-8e28-50d204d2d379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_singularTaxpayerDetails_lastName_asCurrent']</value>
      <webElementGuid>9ac7d9ee-e0b0-467d-a848-c952ca5be61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singularTaxpayerDetailsHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>e31164f1-2fe7-438f-9cf7-0a555b6dc323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>c4b7d140-8c38-4a35-8c55-8d8deffa1e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_singularTaxpayerDetails_lastName_asCurrent']</value>
      <webElementGuid>7dffed33-defe-4b3b-a244-88445bf58653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
