<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CodigoPais</name>
   <tag></tag>
   <elementGuidId>a1bec5c5-c5de-4e7d-b52a-48c5661f8f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'phoneCode_asCurrent_search_0' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Contacto/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='phoneCode_asCurrent_search_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneCode_asCurrent_search_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8187ee04-287a-4643-aa85-a5cc9ab6d47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneCode_asCurrent_search_0</value>
      <webElementGuid>9b28f9ee-38e1-46c0-b391-b3209c88c23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>edbe234f-46f5-4a63-9845-a31af1f1808c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>f06b9693-77ff-4154-86da-f4143421459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>ddca40a2-ac27-4110-a119-5ee4a896c1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>18acbfe0-990f-4bf1-aa3e-78aed6becef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>356a6c37-6b69-4cd3-a390-a82dc19a59d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>bbd6cf3f-7676-4cd5-9e30-664eb4c13ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>9b57a066-207c-4c11-9474-c957081ac8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>phoneCode_asCurrent_search</value>
      <webElementGuid>d6d0917f-b124-46c9-94d7-b6063278d87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>phoneCode_asCurrent_search</value>
      <webElementGuid>0c18e9ff-0e4f-4918-bcfa-ba61c034de15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_phoneCode_asCurrent_search_boGroup_contactInformation_phoneDetailsGroup_phoneDetailsGroupList</value>
      <webElementGuid>8497c46a-78e0-44e4-8772-3230f04f468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneCode_asCurrent_search_0&quot;)</value>
      <webElementGuid>65362371-9c3f-4dd5-907a-d066c158ad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>921175d9-a649-46b8-b686-478cd2843c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='phoneCode_asCurrent_search_0']</value>
      <webElementGuid>ff9d2585-af69-43be-8ff4-601cdea34940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='phone_country_Code']/td[2]/img</value>
      <webElementGuid>08760965-d278-4b3a-8532-ba42bf83fe5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Pesquisar Para Código do País'])[5]</value>
      <webElementGuid>fa61aa1e-d5a0-454b-9dc0-c5c1ba98ca00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/img</value>
      <webElementGuid>576dfae2-a392-4053-a835-241727d734ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'phoneCode_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      <webElementGuid>f013398c-bfbe-459f-9f1d-c4df49349722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
