<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CodigoPaisPrincipal</name>
   <tag></tag>
   <elementGuidId>9cfa919d-9bf3-481f-81ec-35faffe31db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_contactInformation_contact_countryCode_asCurrent_search' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Contacto/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='boGroup_contactInformation_contact_countryCode_asCurrent_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_contactInformation_contact_countryCode_asCurrent_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ca869f0f-bc40-47ea-8717-5db6027639fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_contactInformation_contact_countryCode_asCurrent_search</value>
      <webElementGuid>4211a35a-d021-4fd4-8c04-5f52337b9d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d7dd176f-9bfd-45c1-9031-77c7c08d6cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>9eb4c965-891a-4737-83ee-f136ce8cd33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>0c8b6227-82aa-4c18-b9d8-5048f31aac21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>b776023e-b21c-4a50-b124-1333ae955b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>f3289c74-f76c-4cff-9671-74de6e662f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>5a5d6aae-266c-4c9d-8773-d331870c39eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>a9d0c79a-3aaf-48c9-847e-ed80c334695d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_contactInformation_contact_countryCode_asCurrent_search&quot;)</value>
      <webElementGuid>a6c8e61c-407d-4e1d-9910-d01b02fee3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>d76d6880-45d9-4622-9038-01d28c204786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='boGroup_contactInformation_contact_countryCode_asCurrent_search']</value>
      <webElementGuid>1ea37c84-20dd-42ba-b00d-f10971061d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='contact_country_Code']/td[2]/img</value>
      <webElementGuid>ec1c335f-9b44-4b5c-b75f-3013f47f46cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Pesquisar Para Código do País'])[4]</value>
      <webElementGuid>e9ff3841-a061-4a3e-82cb-7b689e1b487c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>5e520cc3-65b4-4b5d-9199-6150d2c11be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'boGroup_contactInformation_contact_countryCode_asCurrent_search' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      <webElementGuid>40c03b13-cd31-4cc2-bb14-1cbb2a1a8691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
