<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EnderecoWeb</name>
   <tag></tag>
   <elementGuidId>a1d9bef9-9732-43c2-a5fd-17476605bf74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#webAddress_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'webAddress_asCurrent_0' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Contacto/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='webAddress_asCurrent_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc148187-90be-4fe7-aec5-a444bf55955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e151f66d-66d6-444e-8289-ba1f333d8008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this);</value>
      <webElementGuid>2b107c65-e1a6-4c94-8294-3db8cada7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>webAddress/asCurrent</value>
      <webElementGuid>2ca185a7-5244-4da9-8e80-fa1c1dc162e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>192e4f7f-72a1-4796-952c-a85ba35b033a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>61107deb-f081-431c-a6e1-bd919ea14850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b96c2533-c853-409f-af20-057680220ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webAddress_asCurrent_0</value>
      <webElementGuid>0b736f3c-5f46-44dd-a0d9-22fdf4f571ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_WEB_ADDRESS</value>
      <webElementGuid>c7084eec-591c-44cd-a75f-baf9e4cf046d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:200</value>
      <webElementGuid>0a141859-83ae-4509-bf48-7d0975d306aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>webAddress/asCurrent</value>
      <webElementGuid>da141afc-5c2a-40f4-afc0-30628fd97cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>e4992f29-21d3-4e16-982e-7fc40d6a180e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>f3aeacc2-58da-495a-a95d-b8f03871ef54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>e6d7b71e-0661-4b4f-8b3b-831df5f1eeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>webAddress_asCurrent</value>
      <webElementGuid>4e168d5b-18ee-4adc-9534-825f4a14cd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>webAddress_asCurrent</value>
      <webElementGuid>942a21cc-90a4-4b52-a2be-f35b29e3aeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webAddress_asCurrent_0&quot;)</value>
      <webElementGuid>6914f67e-bcd8-429a-bce3-9c8d12a59ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>39822cc2-ac64-4bb6-93ac-e0ba75fa3179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='webAddress_asCurrent_0']</value>
      <webElementGuid>c5bfd62c-b09a-450e-b30f-a3549e5d5226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contactInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[8]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>f9237d9b-9614-4efa-b6bf-072395136ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>71693a9c-84db-4c7e-aa26-615f556a99eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'webAddress_asCurrent_0']</value>
      <webElementGuid>399a6561-7c04-42d3-b2fc-fce7723b371d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
