<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nContacto</name>
   <tag></tag>
   <elementGuidId>31e5d879-cd6e-4363-9cd6-69308b6b6c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'boGroup_contactInformation_contactNumber_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_CONTACT_NUM' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Contacto/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_contactInformation_contactNumber_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_contactInformation_contactNumber_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c137a47-7953-4a76-b2f7-b7d9e9c92b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d65cef24-99e7-4222-afe2-95794b71e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/contactInformation/contactNumber/asCurrent</value>
      <webElementGuid>111779fb-c0bf-46de-9596-aca5f81f96a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>645ec2a7-9be6-47ce-a40c-ad9b27f02928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>46af152b-5f2e-4c83-8577-45a0a9307de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c5bcad9-f85b-4ad0-b690-77f0782f87be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_contactInformation_contactNumber_asCurrent</value>
      <webElementGuid>e40bf04a-c2e9-46a1-99df-a402741ee4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_CONTACT_NUM</value>
      <webElementGuid>67cc6a03-e110-4b86-b940-0be71b1c67c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:14</value>
      <webElementGuid>0366dd1e-c78b-4b17-8eff-e34ab29aed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/contactInformation/contactNumber/asCurrent</value>
      <webElementGuid>9cec3e2a-6e72-414e-a6c5-8f830639ac58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>eca0e18a-3f5f-4a73-b997-1eebc6cc3bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>122713b4-bd18-4d1a-9811-d3c5dbde1ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7ad72e35-97b3-462f-9699-948c54ffc9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_contactInformation_contactNumber_asCurrent&quot;)</value>
      <webElementGuid>715d4018-6344-4d31-9d1b-ff0c6fc507a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>b007f9b8-d120-427c-9075-8d50e83fcff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_contactInformation_contactNumber_asCurrent']</value>
      <webElementGuid>03f0b478-38ba-4658-8dc4-476c1599f2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contactInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>d3929607-a37e-4615-b9bb-919acfc24ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>e502b74d-fbf2-4439-b259-6e94ae5ff22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_contactInformation_contactNumber_asCurrent']</value>
      <webElementGuid>cd342577-371d-4f6e-b7f8-df1cd3c69821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
