<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selecionar</name>
   <tag></tag>
   <elementGuidId>01b855ce-8f0e-4cf6-8693-44b89b961203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Selecionar']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'button' and @src = 'images/select_ena.png' and @alt = 'Selecionar' and @title = 'Selecionar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>882ae56f-e35a-4a14-9224-a9a80c7fcb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/select_ena.png</value>
      <webElementGuid>4e916cce-ba5d-4e4b-9244-a7f1c31c3823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selecionar</value>
      <webElementGuid>3912a8d3-3a40-42d3-8c47-0c0545f4dfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Selecionar</value>
      <webElementGuid>4dc46052-cca9-4034-8be0-3c6b05d0ae7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
