<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>codigoPostal</name>
   <tag></tag>
   <elementGuidId>0290b75b-23cd-4a09-8e76-f5e945dc469c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_secondaryAddressInformation_postalCode_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT POSTAL_CD' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Endereco Secundario/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_secondaryAddressInformation_postalCode_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_secondaryAddressInformation_postalCode_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe2f6a2e-06e6-4067-8850-4fd3002428ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a2d8ff21-365c-4331-b9df-ffc2a25d6a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/postalCode/asCurrent</value>
      <webElementGuid>9defab98-c558-4bfc-9c4f-c07f28aedc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>358e1f23-6b59-4f7b-b9fc-b969f0b58ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c389ba4f-93d2-4172-9eff-c8865d84683d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_secondaryAddressInformation_postalCode_asCurrent</value>
      <webElementGuid>464ce739-7832-4256-89cd-3dbb03ded18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>0a1eba0e-c595-4da7-802c-d3ec6d1fd3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT POSTAL_CD</value>
      <webElementGuid>8bcff1a0-691d-4285-be78-bec1925740ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:12</value>
      <webElementGuid>b9cb47a4-6d6e-41df-a873-465f1dfa4ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/postalCode/asCurrent</value>
      <webElementGuid>02215863-d292-443a-9d1c-c34c9cf99566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>eed65b16-287d-4603-b83e-7d7f3a8ec111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_secondaryAddressInformation_postalCode_asCurrent&quot;)</value>
      <webElementGuid>35c9b68f-4a71-4cac-bbf1-0c4be8a74088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>2bcd3367-1dff-4d12-88e9-866c02237fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_secondaryAddressInformation_postalCode_asCurrent']</value>
      <webElementGuid>2a9f5893-8426-4664-ba32-826435aa7151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='secondAddressSection']/tbody/tr/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>de31f28b-0ad7-4a8b-b052-d484545bcfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>82399ff7-0430-4ccd-91ea-f5eb27be62fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_secondaryAddressInformation_postalCode_asCurrent']</value>
      <webElementGuid>d0ae90f2-f81f-4623-b038-e87e8823e464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
