<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>informacaoComplementar</name>
   <tag></tag>
   <elementGuidId>0cbeb4cc-0634-4b00-851a-3c3a30b074e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_secondaryAddressInformation_complementaryInformation_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_COMPLEMENTARY_INFORMATION' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Endereco Secundario/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_secondaryAddressInformation_complementaryInformation_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_secondaryAddressInformation_complementaryInformation_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac934568-98d1-41e1-af9b-b4eb850371b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>65fa43bd-1de4-4c31-8085-97aa6948e76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/complementaryInformation/asCurrent</value>
      <webElementGuid>944735f4-95a1-402a-a0d1-f5451e47c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>fc31393c-2891-4c88-952d-465c08a636da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b4eb0a9-5782-4e42-acf1-969b5a0953d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_secondaryAddressInformation_complementaryInformation_asCurrent</value>
      <webElementGuid>afec69a3-984c-48b8-b981-6450dc4e3baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>7c2868ff-509c-465e-a73d-1cca5d86c5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_COMPLEMENTARY_INFORMATION</value>
      <webElementGuid>905e63d5-de28-422d-92d2-e1a366cd7684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:64</value>
      <webElementGuid>7b63dd7c-75be-4d54-b9dd-42f1e1ea1557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/complementaryInformation/asCurrent</value>
      <webElementGuid>2eae8ba9-6dd9-481f-80e6-dc96dbbefac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>2776d984-2d63-425e-a8d5-cba7fb93eaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_secondaryAddressInformation_complementaryInformation_asCurrent&quot;)</value>
      <webElementGuid>7e6ed263-8a06-4c4f-a762-5e3474e9d0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>1ad7f902-81be-4dcd-99c0-20338b945b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_secondaryAddressInformation_complementaryInformation_asCurrent']</value>
      <webElementGuid>0e7ee0eb-3aaf-4e78-a2e3-7ec26a9bc212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='secondAddressSection']/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>afbe73b6-e312-4060-b7d1-70011ba60a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>96ed8a39-34aa-4d22-b63b-dc484b130f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_secondaryAddressInformation_complementaryInformation_asCurrent']</value>
      <webElementGuid>b583551a-0232-43da-b1d5-6fc3511f6078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
