<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>residenciaHabitual</name>
   <tag></tag>
   <elementGuidId>05a9c69f-86bb-4499-941f-439bbc391099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'asCurrent' and @id = 'boGroup_secondaryAddressInformation_physicalAddress_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_PHYSICAL_ADDR' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacao de Endereco Secundario/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_secondaryAddressInformation_physicalAddress_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_secondaryAddressInformation_physicalAddress_asCurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4a8dfc9-a942-42ac-8f34-7f9900b82757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ceee4b12-655a-4fa9-b4fb-cf20c4ebe6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/physicalAddress/asCurrent</value>
      <webElementGuid>c48e6fb8-033f-4dd6-ae80-c4ce1e312c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>8c171f67-180a-4265-bd59-b1c3f29dfe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a43916f-1a8f-46ce-af86-b9064e8ee5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_secondaryAddressInformation_physicalAddress_asCurrent</value>
      <webElementGuid>0e51b46d-dfa9-4dfe-b0fc-9640738a9e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>7bb04166-adeb-4b40-906f-43cd5b419c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_PHYSICAL_ADDR</value>
      <webElementGuid>28d23615-6422-4ebb-98f3-650d84046e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:64</value>
      <webElementGuid>1bca35df-6527-416d-8e0b-2fe896ae2882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/secondaryAddressInformation/physicalAddress/asCurrent</value>
      <webElementGuid>9ed9baa2-d0ce-473c-b9df-3e8cdb2b17d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>f80c1997-0c38-4cb8-a3c3-0304cb31af7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_secondaryAddressInformation_physicalAddress_asCurrent&quot;)</value>
      <webElementGuid>44a55122-be15-42b0-b09f-08a619516a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>a927bbb2-8936-443a-8570-063a2f76506d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_secondaryAddressInformation_physicalAddress_asCurrent']</value>
      <webElementGuid>769cc2f8-9db0-43f3-a24c-93d6497f5bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='secondAddressSection']/tbody/tr/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>cd3a7d30-50dd-4478-bd11-386aedf476d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>e9e46232-82fc-443a-9286-4cb8c9d8032f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_secondaryAddressInformation_physicalAddress_asCurrent']</value>
      <webElementGuid>8ecb120a-8693-4b01-95a3-fea65fa6dd15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
