<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>acrescentar</name>
   <tag></tag>
   <elementGuidId>12e4c209-b1cf-4a8b-a7f7-c99144feb74d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;partnersHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/span[1]/img[@class=&quot;imgPlus&quot;][count(. | //*[@alt = 'Acrescentar' and @title = 'Acrescentar' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']) = count(//*[@alt = 'Acrescentar' and @title = 'Acrescentar' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@onclick='oraAddGridRow(event);'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9986d0d-3106-4c0a-9ed3-c34b60b733d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ca3fedcc-9eeb-42bc-ab81-5cbe4e1dc2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/plus.png</value>
      <webElementGuid>f45ec086-fed5-433c-91a0-112e36c1be76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgPlus</value>
      <webElementGuid>dc48560b-637d-4105-9bce-68020082f672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Acrescentar</value>
      <webElementGuid>cf228ffd-c330-4687-b7e8-f303eee6be07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Acrescentar</value>
      <webElementGuid>6eb97720-f1c8-4f87-8992-b3514b67380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraAddGridRow(event);</value>
      <webElementGuid>7fc1e411-0e14-4c02-a2ff-acdcf3777eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraHandleKeyPressEvents(event);</value>
      <webElementGuid>2f0507cc-efe9-471c-966f-9466620785c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnersHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/span[1]/img[@class=&quot;imgPlus&quot;]</value>
      <webElementGuid>a04d54aa-9fdc-4551-be18-a8ceb24cad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>62fd8c1d-817c-495e-819e-a9f6b7be1703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@onclick='oraAddGridRow(event);'])[10]</value>
      <webElementGuid>d34f6cf4-9ff0-4f23-bbf1-920f0259cb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='partnersHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/span/img</value>
      <webElementGuid>ab21df59-b3a6-48ee-a742-3a263da1c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Acrescentar'])[10]</value>
      <webElementGuid>9f144afc-0541-4933-ba92-dce7521dfb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/span/img</value>
      <webElementGuid>99303d5e-bc3f-4642-b14b-8f097acaeca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/alta/plus.png' and @alt = 'Acrescentar' and @title = 'Acrescentar']</value>
      <webElementGuid>87bc2c20-2bc4-4fe0-9350-0fcfd261c26f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
