<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>apagar</name>
   <tag></tag>
   <elementGuidId>1eb450e9-84c3-4462-a14c-b306f31509f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;partnersHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/span[2]/img[@class=&quot;imgRemove&quot;][count(. | //*[@title = 'Apagar' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']) = count(//*[@title = 'Apagar' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@onclick='oraDeleteGridRow(event);'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da962ac6-26d4-406c-a31c-3cabf0d3ca8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1ad84e8e-85f9-4c1a-8554-265a64637b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/remove.png</value>
      <webElementGuid>d8fd57a8-0591-4f7f-9765-97de7d712fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgRemove</value>
      <webElementGuid>04e59f39-811a-4c42-aa5f-144aa74afbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apagar</value>
      <webElementGuid>23905ac0-fe1f-41ea-8f4a-e6410f2e8c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apagar</value>
      <webElementGuid>052e17d5-b5ca-4f24-b066-b902cd4123ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraDeleteGridRow(event);</value>
      <webElementGuid>0d7a8390-231c-4cbd-aca5-92540a68e4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraHandleKeyPressEvents(event);</value>
      <webElementGuid>1d1a230e-96d2-4b89-9a39-faf131e5ca28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnersHeader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;layoutSectionTable&quot;]/tbody[1]/tr[1]/td[1]/span[2]/img[@class=&quot;imgRemove&quot;]</value>
      <webElementGuid>1fa64ebd-55f0-4a3e-8ebb-1b7336c3c462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>879301f0-4be1-4f5b-a341-741978cf64cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@onclick='oraDeleteGridRow(event);'])[10]</value>
      <webElementGuid>4cc9ebc5-a0c1-4278-8d09-3a07b933a001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='partnersHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/span[2]/img</value>
      <webElementGuid>4d1c57cf-a2f6-4c33-899e-9c1d65c325bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Apagar'])[10]</value>
      <webElementGuid>39eba1ee-0722-4cb8-9984-c37431e0e9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/span[2]/img</value>
      <webElementGuid>ddf43224-bfca-431d-8bb7-00a35d59c8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/alta/remove.png' and @alt = 'Apagar' and @title = 'Apagar']</value>
      <webElementGuid>6c8cd3b9-c7da-4ca1-b13d-b450ed2c19ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
