<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentagem</name>
   <tag></tag>
   <elementGuidId>f78b07f8-c3bd-442b-87a5-00b936865738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherCollIdPartnerPercent_asCurrent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollIdPartnerPercent_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_REGFORM_PARTNER_PERCENT' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollIdPartnerPercent_asCurrent_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbe1063c-e6fa-4531-a9fc-f9ede75a7672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a4b0a3cc-93fa-4698-9bef-0021d287666f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>otherCollIdPartnerPercent/asCurrent</value>
      <webElementGuid>f6571637-166e-40e3-91ba-8d9bf04bd301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>8eee96c4-2fbb-4235-a504-41afb1c83f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>f940ca8a-9252-4c20-8f28-d8b3c29c69b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4077be3-c9a3-4cd2-97dc-1c4edf07792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollIdPartnerPercent_asCurrent_0</value>
      <webElementGuid>679db64a-f27a-4dd5-ab80-7e1860cb4827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_REGFORM_PARTNER_PERCENT</value>
      <webElementGuid>994660a1-4718-417c-9829-12c5cb392c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>number;precision:5;scale:2</value>
      <webElementGuid>100a7a46-5b5a-466c-ad05-204a3c7f90d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>otherCollIdPartnerPercent/asCurrent</value>
      <webElementGuid>94139df7-67fc-4e38-b93f-d1135300a42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraNumber</value>
      <webElementGuid>03c05408-3572-4e50-a8ac-c22646acc482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>6f1570ab-42db-419e-aea3-3f83aef919a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>ddeb0710-0786-4627-98b8-89224732c085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollIdPartnerPercent_asCurrent</value>
      <webElementGuid>386d7dc5-e236-4bd9-8614-0c27e4b5cb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollIdPartnerPercent_asCurrent</value>
      <webElementGuid>3eb68cb9-a780-4add-912d-9c36077757a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollIdPartnerPercent_asCurrent_0&quot;)</value>
      <webElementGuid>28216f9b-7799-4921-949f-462d8a8d4a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>6ca43341-0f07-418d-a4da-8e02cb2492c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollIdPartnerPercent_asCurrent_0']</value>
      <webElementGuid>e6056ff4-f512-41d0-929b-b94b108d353d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='partnersHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>6e802ca2-fe8e-4752-9605-24edaa6737e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>95cf1358-c103-499f-a3e6-355c68eaf589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollIdPartnerPercent_asCurrent_0']</value>
      <webElementGuid>4d720a57-06ce-41b4-ab26-64c425153b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
