<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pesquisaNIF</name>
   <tag></tag>
   <elementGuidId>fb2e7776-cd83-4218-958f-f123fe2699d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherCollIdNumber_asCurrent_search_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollIdNumber_asCurrent_search_0' and @title = 'Pesquisar Para Nº de Identificação' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao dos Socios/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='otherCollIdNumber_asCurrent_search_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9828d11-070a-42b8-90a8-dbbea45d099a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollIdNumber_asCurrent_search_0</value>
      <webElementGuid>55c907dc-d702-4af3-8dc1-426041840a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a86a50b5-4584-4047-8546-b9e737bb63af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>05e2999f-a2e4-4597-8994-dbd6ecd81729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>2304358e-95e8-4958-848f-0bf432c1f276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Nº de Identificação</value>
      <webElementGuid>6e316b17-7948-4761-a3c1-6486b9d8eccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Nº de Identificação</value>
      <webElementGuid>5c135843-9641-4e3d-92fc-8663497b4ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>83f9bf70-f5a3-489b-9db5-a3ef3cb70b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>fc005f0a-8e96-4d86-9332-e71899dff76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollIdNumber_asCurrent_search</value>
      <webElementGuid>e54c5090-8b6f-4c3d-9ac8-ce6a67be94ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollIdNumber_asCurrent_search</value>
      <webElementGuid>36ee43ce-f0ad-4a77-90b1-da06fb4f3756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_otherCollIdNumber_asCurrent_search_boGroup_partners_otherCollPartnerDetailsGroup_otherCollPartnerDetailsGroupList</value>
      <webElementGuid>680253f7-f018-4462-b3c8-87f724bc696a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollIdNumber_asCurrent_search_0&quot;)</value>
      <webElementGuid>d1bb73d5-ff29-462f-92e9-1e0652c0a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>65da021c-e584-4aea-8d6c-6dd7b278d430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='otherCollIdNumber_asCurrent_search_0']</value>
      <webElementGuid>9bb09e77-d946-44af-9480-2e10696e470b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='partnersHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>02110212-b306-468f-a387-9a6c59036769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pesquisar Para Nº de Identificação']</value>
      <webElementGuid>0f4e440b-ff69-4967-9b19-bbfeaa3ea38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/img</value>
      <webElementGuid>6cbc02be-0627-4e26-9a35-1520f3202b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'otherCollIdNumber_asCurrent_search_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Nº de Identificação' and @title = 'Pesquisar Para Nº de Identificação']</value>
      <webElementGuid>79eb9b82-0e18-4f75-987d-7a63530ccaaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
