<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expandirContextoAtual</name>
   <tag></tag>
   <elementGuidId>45abf6e1-3426-4ab6-8f0a-6fb9daa00880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='collapse_201']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;zoneHeader201&quot;]/table//*[@id=&quot;expand_201&quot;][count(. | //*[@ref_element = 'Object Repository/Page/Principal/dashboard']) = count(//*[@ref_element = 'Object Repository/Page/Principal/dashboard'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse_201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;zoneHeader201&quot;]/table//*[@id=&quot;expand_201&quot;]</value>
      <webElementGuid>58b94337-5224-4536-9779-90e3cb273ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/dashboard</value>
      <webElementGuid>7b2ef42f-e1c9-45cc-b4e5-62ed49306f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='collapse_201']</value>
      <webElementGuid>e829758e-6005-409e-92ab-54324364289c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='zoneHeader201']/table/tbody/tr/td/img</value>
      <webElementGuid>aee09cbb-a780-434c-813e-751a271057d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Collapse Contexto Atual zone']</value>
      <webElementGuid>52dfead8-fea1-4938-9dd7-eedff94ee688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td/img</value>
      <webElementGuid>d1fed7ff-566d-415a-abbf-f210a6fb983f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'collapse_201' and @src = 'images/alta/discloseExpanded_ena.png?ltr' and @alt = 'Collapse Contexto Atual zone' and @title = 'Collapse Contexto Atual zone']</value>
      <webElementGuid>ea99d916-4a24-4447-950b-87a968bf6e94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
