<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuAlterarFormularioDeCadastro</name>
   <tag></tag>
   <elementGuidId>9178ea8f-03a9-4e21-a83a-68acf20200cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='CI_CONTEXTPERSON_subMenuItem0x1']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;CI_CONTEXTPERSON_subMenuItem0x1&quot;)/span[1][count(. | //*[@ref_element = 'Object Repository/test/newtest/Page_Formulrio de Cadastro/frame_Navegador no suportado_main']) = count(//*[@ref_element = 'Object Repository/test/newtest/Page_Formulrio de Cadastro/frame_Navegador no suportado_main'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ec15631d-5997-4e1d-8e75-c2e7e4f110df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuobj</name>
      <type>Main</type>
      <value>contextPerson</value>
      <webElementGuid>71a74bcc-8a31-42e6-9438-e51a62d9aa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alterar formulário de Cadastro</value>
      <webElementGuid>d73bf62e-d665-4401-98b7-eac872aeda71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CI_CONTEXTPERSON_subMenuItem0x1&quot;)/span[1]</value>
      <webElementGuid>04cb41c4-b098-42e6-8f1f-06d3c4298401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_main</value>
      <webElementGuid>33617ad5-d315-4a88-8d3a-5565d2779fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='CI_CONTEXTPERSON_subMenuItem0x1']/span</value>
      <webElementGuid>b7b0d32a-3248-49dd-b16b-b58f84e5790d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir Para Formulário de Cadastro'])[1]/preceding::span[2]</value>
      <webElementGuid>adf5486f-a074-42c1-a2c7-ffabd13fca20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir Para Contacto do Cliente'])[1]/preceding::span[4]</value>
      <webElementGuid>70809646-ef33-4308-914f-584c534a3572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alterar formulário de Cadastro']/parent::*</value>
      <webElementGuid>9c3af15c-89ee-49e1-ba68-98fa574e1db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>1211cae5-2929-4aec-9f9a-07fc93b0d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Alterar formulário de Cadastro' or . = 'Alterar formulário de Cadastro')]</value>
      <webElementGuid>0bcf1702-168a-4946-afdc-e435b71a1904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
