<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesquisarNifDaEmpresaMae</name>
   <tag></tag>
   <elementGuidId>42e6fa55-91b4-4e05-bfba-45adb66f0206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollNIFHoldCompConsGrp_asCurrent_search_0' and @aria-labelledby = 'gridTbl_h_otherCollNIFHoldCompConsGrp_asCurrent_search_boGroup_otherCollCapIntCompConGrpsGrp_otherCollCapIntCompConGrpsGrpList' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollPhoneNumber_asCurrent_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollPhoneNumber_asCurrent_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollNIFHoldCompConsGrp_asCurrent_search_0</value>
      <webElementGuid>091c289c-8c37-46e0-9f3c-b16eb17e8ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_otherCollNIFHoldCompConsGrp_asCurrent_search_boGroup_otherCollCapIntCompConGrpsGrp_otherCollCapIntCompConGrpsGrpList</value>
      <webElementGuid>2990b487-d2c5-4414-9422-a596ff5f3c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>2aefb393-241b-4224-93c0-50ecd469a4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollPhoneNumber_asCurrent_0_0']</value>
      <webElementGuid>6b8f7ccc-76d7-4763-9dc8-b3bac708bc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[26]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>2edb6abf-c8ff-4cfd-9fc3-6da67fb83be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[26]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>59d84d3a-bf41-4d05-b237-ee46282b5ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollPhoneNumber_asCurrent_0_0']</value>
      <webElementGuid>8b06f55d-5677-4376-b1ad-5340681b89a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
