<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnRemoverNifDaEmpresaMae</name>
   <tag></tag>
   <elementGuidId>b2d13d52-2677-4a63-af0a-bc7652df69f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'removeNIF' and @title = 'Delete' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollPhoneNumber_asCurrent_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollPhoneNumber_asCurrent_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>removeNIF</value>
      <webElementGuid>4b4aed66-679d-4fc5-888e-093504ef6f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>1498eafe-71e0-44d0-987f-57b4ec6dea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>b32ccd5a-187b-4c8d-a3b1-da97fb6426e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollPhoneNumber_asCurrent_0_0']</value>
      <webElementGuid>3ffe6884-912b-473e-b507-9a683d8773fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[26]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>4a04a474-325f-494d-843a-22a4fb2cd201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[26]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>a5050b12-54c7-430a-b4fc-1539aa94a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollPhoneNumber_asCurrent_0_0']</value>
      <webElementGuid>da5931c2-4bb0-4c9e-bbf2-53edc985f28e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
