<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>comuna</name>
   <tag></tag>
   <elementGuidId>4479560c-9750-4a74-a0bc-12c3ba7ca526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollSelectSubsCommune_asCurrent_0' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollSelectSubsCommune_asCurrent_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='otherCollSelectSubsCommune_asCurrent_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bb164de-1e55-4d72-acbb-aadfd6227c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>communeSelector</value>
      <webElementGuid>1fa033d7-9b09-44aa-bc94-b9ce7b934d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollSelectSubsCommune_asCurrent_0</value>
      <webElementGuid>17531193-db6c-47a5-ade8-e020f2d5f6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>781298f1-9eaf-44f7-837a-bda8a111ae69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('COMM',this);populateBranchMap(this);</value>
      <webElementGuid>97bc6a22-8c86-4480-afb2-44a9db1edf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb4b4abd-1885-4cfd-983a-c685188333c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_COMMUNE</value>
      <webElementGuid>fd40da37-ac0d-4fcd-b615-0192ca642e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>e5174215-ec1a-418f-b10d-bfec34b0190f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollSelectSubsCommune_asCurrent</value>
      <webElementGuid>9672274d-a997-4f45-9ea4-e6b4676018f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollSelectSubsCommune_asCurrent</value>
      <webElementGuid>8351e7ff-4507-4cb5-938d-1b788d671e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBRIZBELA VISTATABI</value>
      <webElementGuid>bafadc8f-c73c-4ca1-8acd-179f2bb5e154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollSelectSubsCommune_asCurrent_0&quot;)</value>
      <webElementGuid>c51a5f1b-74ff-4a19-bacc-06209df3cdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>c150af6c-7b0f-4271-bfdf-2fb7e582a28d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='otherCollSelectSubsCommune_asCurrent_0']</value>
      <webElementGuid>71101bb0-48f1-436d-8bb3-19d3eedc1632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[9]/td[2]/select</value>
      <webElementGuid>5f45339e-bc50-456e-809e-cf5805130cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[5]/following::select[1]</value>
      <webElementGuid>c273ed1c-b43f-4797-a973-697b6b9ae0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[7]/following::select[2]</value>
      <webElementGuid>24bab3ea-f54f-4015-9ed4-1d9030dc040f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localidade'])[4]/preceding::select[1]</value>
      <webElementGuid>2cf60d59-ba8d-4a21-943d-ce1b9077386a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bairro'])[4]/preceding::select[1]</value>
      <webElementGuid>e310c9d8-eb2c-4d17-b936-22f6221a2bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[9]/td[2]/select</value>
      <webElementGuid>3554f7b6-8436-4367-8e63-c361f3a7584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'otherCollSelectSubsCommune_asCurrent_0' and @type = 'text' and (text() = 'AMBRIZBELA VISTATABI' or . = 'AMBRIZBELA VISTATABI')]</value>
      <webElementGuid>685117d6-2f37-4da2-ae8e-3fc435734e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
