<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>conta</name>
   <tag></tag>
   <elementGuidId>2fe9ab50-8d56-4bd0-a345-85f6d03c86be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'CM_OC_ACCOUNT_L' and @oramdlabel = 'CM_OC_ACCOUNT_L']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollSubsFloor_asCurrent_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollSubsFloor_asCurrent_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CM_OC_ACCOUNT_L</value>
      <webElementGuid>e0956328-f0af-4c97-91a9-892318d71cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oramdlabel</name>
      <type>Main</type>
      <value>CM_OC_ACCOUNT_L</value>
      <webElementGuid>acaa20ac-535d-4778-b027-bc09941a70fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>91fcb4a2-1cfb-40dc-a6d8-c88ef2fce89e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollSubsFloor_asCurrent_0']</value>
      <webElementGuid>98e074be-0ae0-416e-b149-6ef52db07eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>4e59918f-e31b-432a-8ca3-2b1d09d02677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>37c4250e-7d88-4e77-87bd-0a50d4d3abc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollSubsFloor_asCurrent_0']</value>
      <webElementGuid>22d340c7-8b30-4386-98d7-8eeb9dde780a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
