<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email</name>
   <tag></tag>
   <elementGuidId>13c48720-b6e4-4bf1-8d04-75d9f71f24fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollEmail_asCurrent_0_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollEmail_asCurrent_0_0' and @aria-labelledby = 'C1_AS_CURRENT CM_AC_EMAIL' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao de Agencias/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollEmail_asCurrent_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>503f2404-c1d3-4da5-8b34-8924cde198e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>28737813-3781-42ec-8936-a452a2056725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setPkChild(this);</value>
      <webElementGuid>1d7e596d-5905-411e-9c15-0970dd1c013c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>otherCollEmail/asCurrent</value>
      <webElementGuid>abf90aaa-550d-4d7c-bb9c-c2866a801c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>44307aae-2928-4da2-abf0-694e9cfdecf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>7b73d429-b882-474b-8800-b2f028a52087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2fcb04c-5e7e-4a0e-b62c-bc93f40b5d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollEmail_asCurrent_0_0</value>
      <webElementGuid>d900f835-5425-4d78-a567-ed85e3e0fe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_AC_EMAIL</value>
      <webElementGuid>da9517a0-9c2c-4d3b-87ce-244fba04a272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:256</value>
      <webElementGuid>4987ac82-8dbd-4d83-bb95-5ab7c085e7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>otherCollEmail/asCurrent</value>
      <webElementGuid>243e164f-3d29-4721-9453-a1a67c58417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>154c1437-73cf-454f-8922-dbc8c29566f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>e0fb2b83-ee30-4d9c-a86e-2735316cb3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>2256d311-0f84-4804-9c30-ffae05cd4ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollEmail_asCurrent</value>
      <webElementGuid>c3a2231a-07d6-47cc-bd96-4f4f79827062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollEmail_asCurrent</value>
      <webElementGuid>6b94dfd6-aa6b-41ff-816e-5c61eeb81605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollEmail_asCurrent_0_0&quot;)</value>
      <webElementGuid>5542040c-9805-4a65-9d93-114bdbcd6d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>79737038-819e-447c-8470-91eb6279bd04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollEmail_asCurrent_0_0']</value>
      <webElementGuid>ecdf0535-ee55-4571-9c82-e77a8f794947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[28]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>e0ede3e9-2635-400d-8b01-a4b3fedab5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>8daeec5b-36d6-4503-bb1e-905f2940f4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollEmail_asCurrent_0_0']</value>
      <webElementGuid>77c2e951-97ea-494c-ae8a-2f402e793c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
