<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>localidade</name>
   <tag></tag>
   <elementGuidId>61c67089-297b-4e79-a975-df07db609f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherCollSubsLocality_asCurrent_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollSubsLocality_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_LOCALITY' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao de Agencias/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollSubsLocality_asCurrent_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e04afe7a-1178-4166-bb4a-b4ad4efdb416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0a918343-87f0-4052-84cc-0972002a93e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>otherCollSubsLocality/asCurrent</value>
      <webElementGuid>86534755-e2e3-41fe-92c5-ed0d0a63530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>2fb9056b-deb3-4464-96c6-ab9a31e1a9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>c34133a1-57ac-49c3-b2ff-8edd488edfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3e60945-958b-4cb2-9e0f-9bd57f0263c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollSubsLocality_asCurrent_0</value>
      <webElementGuid>a5cf9310-cc05-45d3-bce0-fd15b7ff13dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_LOCALITY</value>
      <webElementGuid>04265efd-239c-48e2-aa3c-29c3e042f6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:50</value>
      <webElementGuid>d3be3bb4-f2e7-4bf2-b8de-bd792015e84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>otherCollSubsLocality/asCurrent</value>
      <webElementGuid>0a3f44c9-7a64-455a-8df9-90d49788cf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>d6ede0d8-dbad-47f9-89f3-7638b959f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>430bc592-a7ef-450f-92f7-3a56d4ccb310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>40ebcb81-c0ec-40a9-ae29-dc6b232f34d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollSubsLocality_asCurrent</value>
      <webElementGuid>3465325b-52f6-4be8-b1d4-e4e305628b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollSubsLocality_asCurrent</value>
      <webElementGuid>25265953-770c-4651-99b0-ed33eccf26a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollSubsLocality_asCurrent_0&quot;)</value>
      <webElementGuid>d031833b-3893-4a00-847a-5e86c9e8df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>5ca043ba-3f86-4b50-91c1-0e53f5ca58d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherCollSubsLocality_asCurrent_0']</value>
      <webElementGuid>ce936bb7-f7a2-400d-9ac6-bc6b7d87178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>451df722-bf6a-4ab9-9085-27228d2c3293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>a2e0b329-deaa-4ef2-a61b-ecd8413a4869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'otherCollSubsLocality_asCurrent_0']</value>
      <webElementGuid>9201c5ba-12d1-4b21-80b3-b36313d84263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
