<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lupaPesquisa</name>
   <tag></tag>
   <elementGuidId>9fc1d70f-3ac1-407b-b98e-6c5a112f3068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='othercoll_phoneCode_asCurrent_search_0_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'othercoll_phoneCode_asCurrent_search_0_0' and @title = 'Pesquisar Para Código do País' and @ref_element = 'Object Repository/Page/Foreign only Coutry Code Search/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#othercoll_phoneCode_asCurrent_search_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d3b1e9a3-b210-4a34-a77d-a138a4b3995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>othercoll_phoneCode_asCurrent_search_0_0</value>
      <webElementGuid>d31a532a-5058-4381-8c4d-95ed349443f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>60f8c391-c33d-4ad3-9a1f-121bdcc07b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>50bbd9ea-8b2a-455c-9203-bd844be4df40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imageTypeElement uiMargin oraSearchImg</value>
      <webElementGuid>39533eab-b373-4c6c-a94f-f9193dd67aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>920111e6-7f78-4232-ac79-7e93f436c265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para Código do País</value>
      <webElementGuid>b7cd13b6-b8b8-404c-90f0-6a712efd9e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>oraOpenSearchImgKeyPressEvent(event);</value>
      <webElementGuid>9aef5165-d6d6-47e1-a14b-592aa5bb1b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>oraOpenSearchImgClickEvent(event);</value>
      <webElementGuid>6b3fe2cd-1637-4ccd-8fa9-aa5aaa93ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>othercoll_phoneCode_asCurrent_search</value>
      <webElementGuid>43880fd2-b6e5-4d8a-ac56-b78197205406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>othercoll_phoneCode_asCurrent_search</value>
      <webElementGuid>99a6a17e-02a4-4333-aa10-cf8b2bea4aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>gridTbl_h_othercoll_phoneCode_asCurrent_search_otherCollPhoneDetailsGroup_otherCollPhoneDetailsGroupList</value>
      <webElementGuid>dac75be7-8b5f-47b7-a84c-95d1bd918a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;othercoll_phoneCode_asCurrent_search_0_0&quot;)</value>
      <webElementGuid>fb91ba67-30f8-4e0c-a904-d6f8f4e216c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>727ed58f-6ce9-4e65-a54e-36e094eb2d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='othercoll_phoneCode_asCurrent_search_0_0']</value>
      <webElementGuid>3bf6edf6-42d3-4ab8-8a1e-e28a3eb0e82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='phone_country_Code_col']/td[2]/img)[3]</value>
      <webElementGuid>64791288-b979-4f26-8e8b-973539baf851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Pesquisar Para Código do País'])[6]</value>
      <webElementGuid>312bde33-7b09-4f92-bc37-c2a8c88185d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[26]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td[2]/img</value>
      <webElementGuid>9a1bf60e-4171-459f-afdd-bd58f49fd548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'othercoll_phoneCode_asCurrent_search_0_0' and @src = 'images/alta/search.png' and @alt = 'Pesquisar Para Código do País' and @title = 'Pesquisar Para Código do País']</value>
      <webElementGuid>aa3994b7-9c1d-4bb6-9406-992054f8c02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
