<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>municipio</name>
   <tag></tag>
   <elementGuidId>c76eb628-55d7-4aff-834b-78e73a63921a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='otherCollSelectSubAndBranchMunicipality_asCurrent_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollSelectSubAndBranchMunicipality_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_MUNICIPALITY' and @ref_element = 'Object Repository/Page/Principal/frame_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollSelectSubAndBranchMunicipality_asCurrent_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c69c8a3d-d1db-4b75-9164-eb961c169d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>municipalitySelector</value>
      <webElementGuid>3eab1801-9d10-47bc-a763-5649f2aee65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchMunicipality_asCurrent_0</value>
      <webElementGuid>127f767d-d1bb-4eb5-b716-0aff308429fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2043e0e8-3320-4853-b3c5-05a963f58d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('MUNI',this);</value>
      <webElementGuid>e5438c08-c0bf-42e6-a443-cb92627164cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ffc36a7-d585-4d09-a0e1-d0064129436d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_MUNICIPALITY</value>
      <webElementGuid>a040ed80-4e9f-4657-86cd-638bed0de63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>1a425a78-8d2c-47c1-95a5-0ffcbc348adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchMunicipality_asCurrent</value>
      <webElementGuid>dccf7372-320c-46a3-8b5b-b37997f800a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchMunicipality_asCurrent</value>
      <webElementGuid>710e1be3-1950-44f4-bd69-00e7707c780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM</value>
      <webElementGuid>f547a9fa-f019-424b-ad5e-b14e324a96d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollSelectSubAndBranchMunicipality_asCurrent_0&quot;)</value>
      <webElementGuid>604ac0fd-3dde-40a9-9348-5cf476d27b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>d6fa6816-1cb8-4a31-a567-b2e0c4cb5a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='otherCollSelectSubAndBranchMunicipality_asCurrent_0']</value>
      <webElementGuid>a3a05140-e2b6-42a6-b972-10f1cd7bfb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>d209d30e-188f-4137-a4c0-6b7b9d031caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[7]/following::select[1]</value>
      <webElementGuid>7ae6a092-90b2-4854-b3d6-3a86c4141377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[5]/following::select[1]</value>
      <webElementGuid>eddcc598-5226-41f8-a01d-636ecc24141c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna/Distrito Urbano'])[5]/preceding::select[1]</value>
      <webElementGuid>8c9c30fe-fd3c-4d41-bbdf-f3221ad79618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localidade'])[4]/preceding::select[2]</value>
      <webElementGuid>90af0c02-5075-4596-89c9-c86487d607b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>a7eb8554-3776-4842-9af6-c310f1df17ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'otherCollSelectSubAndBranchMunicipality_asCurrent_0' and @type = 'text' and (text() = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM' or . = 'AMBRIZBULA ATUMBADANDEDEMBOSNAMBUANGONGOPANGO ALUQUÉM')]</value>
      <webElementGuid>a9f2bddd-085e-49b5-bd81-279ae4bfbe27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
