<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>provincia</name>
   <tag></tag>
   <elementGuidId>daeedb40-643d-4b09-9340-24a66e4a6b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='otherCollSelectSubAndBranchProvince_asCurrent_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'otherCollSelectSubAndBranchProvince_asCurrent_0' and @aria-labelledby = 'C1_AS_CURRENT CM_PROVINCE' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Identificacao de Agencias/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherCollSelectSubAndBranchProvince_asCurrent_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae730217-dea5-4263-87b8-ca832dbbfdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>provinceSelector</value>
      <webElementGuid>59dcae64-9727-4ac5-aa70-47e8a4cd7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0c7842b8-5cad-401e-81ab-e1d0b5436289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchProvince_asCurrent_0</value>
      <webElementGuid>799414fd-ea41-4805-b005-c3193b7785ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addressHandler('PROV', this);</value>
      <webElementGuid>52801e64-a8b1-499f-a896-04e930ddf798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cd68881-93d4-4d92-a430-72fa1e418354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_PROVINCE</value>
      <webElementGuid>b9173206-a8ee-46ad-a0b9-6a936bd99403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>7e9123bf-505c-4e7f-90be-4a650c48b09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id_bk</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchProvince_asCurrent</value>
      <webElementGuid>ccdac734-04fb-4df9-9250-a31f4e7f5e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelid</name>
      <type>Main</type>
      <value>otherCollSelectSubAndBranchProvince_asCurrent</value>
      <webElementGuid>822478ca-3b99-43bd-a61f-be3ae1acd76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE</value>
      <webElementGuid>661e6ffa-b1c0-4e3b-8201-1f83b0219666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherCollSelectSubAndBranchProvince_asCurrent_0&quot;)</value>
      <webElementGuid>07e911c4-b874-48e3-8d76-4be452416977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>64f0f9a6-7ef1-401f-9269-8bb492ab6d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='otherCollSelectSubAndBranchProvince_asCurrent_0']</value>
      <webElementGuid>d7963fcf-d4f7-458c-964e-10ff7cb4bf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subsidiariesHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>939bfe0f-0d44-45dd-ad89-c1129d0a7976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Província'])[7]/following::select[1]</value>
      <webElementGuid>3b9a687c-2488-4405-b9c2-963fe4ba3230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominação'])[2]/following::select[1]</value>
      <webElementGuid>07b7ecba-5d89-412b-aa97-7c814f7444cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autarquia'])[5]/preceding::select[1]</value>
      <webElementGuid>a09aa65d-6985-4598-9855-097eb0eabd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[7]/preceding::select[1]</value>
      <webElementGuid>9c6f35a0-58b6-4f64-8a48-1aeb5b9754e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>b93378df-2516-486f-8266-e9b908d7594a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'otherCollSelectSubAndBranchProvince_asCurrent_0' and @type = 'text' and (text() = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE' or . = 'BENGOBENGUELABIÉCABINDACUANDO CUBANGOCUANZA NORTECUANZA SULCUNENEHUAMBOHUÍLALUANDALUNDA NORTELUNDA SULMALANJEMOXICONAMIBEUÍGEZAIRE')]</value>
      <webElementGuid>ca39b512-696c-4df9-89c8-94633d52c7c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
