<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>casa</name>
   <tag></tag>
   <elementGuidId>5d4e833e-4789-415d-9a43-4b1149cefb2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_alternativeAddressInformation_house_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_alternativeAddressInformation_house_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_alternativeAddressInformation_house_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_HOUSE' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de enderecos alternativos/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e04c1a24-f74b-4487-aef1-f0ce3a9dddf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>da889d97-f72a-4b28-a5e9-73d105dda77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/house/asCurrent</value>
      <webElementGuid>8510185f-28ee-461b-87a7-c69a6b8dcf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>e30c813f-1d43-4cc7-a5a0-6096cf9ecd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>4dc2502b-79a4-4e26-88db-55a87f2b667e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbcb3241-0271-4986-bd80-0c2cdbf46935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_alternativeAddressInformation_house_asCurrent</value>
      <webElementGuid>dcbc0ec5-a2ae-43e2-b65f-1082126887f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_HOUSE</value>
      <webElementGuid>8df244a6-ee45-4384-bddc-bc4f91748e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:10</value>
      <webElementGuid>4024e21c-d80a-4b3d-a6d7-04f9ee69408a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/house/asCurrent</value>
      <webElementGuid>6c1c1d6f-0350-483d-97c7-417a79a0ed1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>3cf182a5-b0b4-4520-876b-7872996d2b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c5ef7be9-8963-4bd3-9b26-a0ac71d41aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b8f4ef1f-4c1d-45c2-a556-36376b968dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_alternativeAddressInformation_house_asCurrent&quot;)</value>
      <webElementGuid>ae90eab1-6882-4f68-92ac-01e3091167f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>f3a7a636-8416-4621-93da-3e60205a687e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_alternativeAddressInformation_house_asCurrent']</value>
      <webElementGuid>d7ac4160-3a26-4f56-bf14-aedbea68d764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alternativeAddressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>b573e6ba-61d5-4066-b243-1cb3d0ac2b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>2a84024d-c6e3-4839-86e9-6aa6b8f718b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_alternativeAddressInformation_house_asCurrent']</value>
      <webElementGuid>7f921960-1e20-47ee-90a3-cdaf029cb2ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
