<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>codigoPostal</name>
   <tag></tag>
   <elementGuidId>4588ad31-d7a4-4a9b-aa00-ef8618c94ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT POSTAL_CD' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de enderecos alternativos/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33483e4d-0353-443d-9d67-6765bf961d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>92d9e934-f8c8-422a-ba6a-6981e78c200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativePostalCode/asCurrent</value>
      <webElementGuid>98de63af-2203-4e9c-8cc0-4a6121a4fd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>5300d7b1-c904-405b-b5cc-39bbd8b85a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>8a3e8f86-5c5b-490f-bae5-1a1104454a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>596c9492-4c20-446f-ba61-3e9e7cf9cf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent</value>
      <webElementGuid>1f54af8b-2bf0-41a5-8cfc-56f873457580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT POSTAL_CD</value>
      <webElementGuid>ad6645c2-908e-4f72-8dee-9dc87f161d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:12</value>
      <webElementGuid>9d8bd86c-ffe0-47c0-b593-bad90f983684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativePostalCode/asCurrent</value>
      <webElementGuid>3d52bcd8-3629-4ae7-b092-f44c34216d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>b345021c-c5f4-4861-a1ea-0abd5fa79b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>277c7ae4-6887-4613-ae01-cf9c8933ad4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>bdbd71b7-aed0-4170-8d81-5d4c9e45a68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent&quot;)</value>
      <webElementGuid>f5d3ff87-666d-40f4-a3f8-1adc2ce5b7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>1de62b06-308f-42b4-8c1f-ec1477869b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent']</value>
      <webElementGuid>37ae6e48-1ecd-4007-8941-99da245f1e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alternativeAddressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>12774cdb-e71e-45a5-b2e9-153b02c003a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>e452d323-cafd-4685-be97-a953996b0adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_alternativeAddressInformation_alternativePostalCode_asCurrent']</value>
      <webElementGuid>783a4fee-463f-4462-8eec-a348c736ff39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
