<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>informacaoComplemenar</name>
   <tag></tag>
   <elementGuidId>5d8bfa1a-3ffd-45b7-ad0b-6f7c37618c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_COMPLEMENTARY_INFORMATION' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de enderecos alternativos/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>089b84a0-e520-4793-82bf-b3d10ea6efbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>95357a2e-bc09-4828-b8d5-93dbc34791af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativeComplementaryInfo/asCurrent</value>
      <webElementGuid>3f47ae65-c96d-4227-b98b-5cfe01d78759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>63d0e745-23a1-4ca1-9242-77bb2fa4ca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>63c2d0b0-68e2-41bc-8271-86f73daf259b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>521fc5f0-008e-4ec6-ae8d-f215df3da1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent</value>
      <webElementGuid>bd00c013-9be4-4bf2-8087-bc9d1242c8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_COMPLEMENTARY_INFORMATION</value>
      <webElementGuid>1196777a-bfd3-41d9-8bdd-73ddec1f1e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:64</value>
      <webElementGuid>f1f7ddb4-693c-48b5-bc00-57e5f252dcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativeComplementaryInfo/asCurrent</value>
      <webElementGuid>e4f13531-d335-452f-ad87-87e6d8d5bb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>d740ee3e-2cb0-4032-8eae-d64e66e2bead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>c101905c-dba3-4921-8cf4-2290108d2651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>d6436111-3d26-433a-9712-1f2d3321a5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent&quot;)</value>
      <webElementGuid>e025a53b-a078-4164-8d70-74e2ab5bd5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>99848741-5969-43f6-aade-c1072c249f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent']</value>
      <webElementGuid>a7dcd457-b891-44e0-889f-5395cb48643a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alternativeAddressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[16]/td[2]/input</value>
      <webElementGuid>9ab84be5-9239-40ee-9e19-25dd1f09e28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[16]/td[2]/input</value>
      <webElementGuid>d1ec24a9-2a4a-4f45-bd4b-7924e289fced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_alternativeAddressInformation_alternativeComplementaryInformation_asCurrent']</value>
      <webElementGuid>f2e4076d-e991-4fae-b880-daef73f6f97d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
