<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rua</name>
   <tag></tag>
   <elementGuidId>9f8c84bf-afd2-4062-859a-4e0470850bc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boGroup_alternativeAddressInformation_street_asCurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boGroup_alternativeAddressInformation_street_asCurrent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_alternativeAddressInformation_street_asCurrent' and @aria-labelledby = 'C1_AS_CURRENT CM_STREET' and @ref_element = 'Object Repository/Page/Formularios/Cadastro/Adicionar/nav_Informacoes de enderecos alternativos/Page_Pesquisa a 360 Graus/iframe_Nmero do Pedido de Servio_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dd044aa-1a2a-4737-a4fb-5dba0d64780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c924a2b8-bfe2-4463-82f5-4291effc21e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativePhysicalAddress/asCurrent</value>
      <webElementGuid>5514e876-24ce-4ceb-b7b4-63a746d59bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asCurrent</value>
      <webElementGuid>207f0003-c4f6-4e6a-a43c-5ea5f6fa735f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>toUpper(this);</value>
      <webElementGuid>8f6995c9-0440-4653-8a23-30872b6899b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e4689fd-2f34-47bf-a526-f75d81bb0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_alternativeAddressInformation_street_asCurrent</value>
      <webElementGuid>70140d83-efd9-4b83-950e-01bdbdd48219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C1_AS_CURRENT CM_STREET</value>
      <webElementGuid>69902e54-5efd-4dae-88d6-c6fd33572cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:254</value>
      <webElementGuid>a0d9c93a-33a3-44e5-aa7d-1db02906647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>boGroup/alternativeAddressInformation/alternativePhysicalAddress/asCurrent</value>
      <webElementGuid>88cef071-dd59-4089-914a-e900a1fa0743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault oraError</value>
      <webElementGuid>23166095-cf08-471a-ac85-fd5847c996db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>77685a5a-5f16-4a8b-bdc3-5c2a57fbbe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>062713c4-c81d-409b-a1a4-603de7ab4920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boGroup_alternativeAddressInformation_street_asCurrent&quot;)</value>
      <webElementGuid>daec6e1b-8f3f-4b24-99e3-d78137851b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>19fdab6b-e67c-4596-8e81-f959c8ccf8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boGroup_alternativeAddressInformation_street_asCurrent']</value>
      <webElementGuid>3d07b2e0-a233-4a6e-844b-675d45dfb7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alternativeAddressInformationHeader']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>2844edc0-517d-480a-837b-7479ff62c7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>1a77352f-ee3d-4e08-9a35-3b7075131f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'asCurrent' and @type = 'text' and @id = 'boGroup_alternativeAddressInformation_street_asCurrent']</value>
      <webElementGuid>3991ce75-b20f-46ae-8462-8f2479439070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
