<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numeroFiscal</name>
   <tag></tag>
   <elementGuidId>a62b6539-a9b8-4ab9-9b66-c306aec085ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='boGroup_taxpayerDetails_nif_asCurrent_search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'boGroup_taxpayerDetails_nif_asCurrent_search' and @title = 'Pesquisar Para NIF' and @ref_element = 'Object Repository/Page_Principal/frame_uiMap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boGroup_taxpayerDetails_nif_asCurrent_search</value>
      <webElementGuid>459a1c12-759e-4421-9fa6-9e7d451f95a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar Para NIF</value>
      <webElementGuid>ffadc8b2-f102-461b-b27e-338af7bb1603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/alta/search.png</value>
      <webElementGuid>e0e824ab-5fb3-4f00-b728-9db3f957ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_uiMap</value>
      <webElementGuid>4f303f37-7110-4263-8b5b-bfe1f4f8bf1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
