<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zoneMapFrame_2</name>
   <tag></tag>
   <elementGuidId>b2273551-f80f-400c-885b-0e30b9791dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;zoneMapFrame_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;zoneMapFrame_2&quot;]</value>
      <webElementGuid>2db66816-179b-4e2e-81f2-94292c7f8c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page/Principal/frame_tabPage</value>
      <webElementGuid>01bc38ba-6705-4235-a0f1-72bbca7433f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
